### ISSUE TITLE
[Bug]: Getting exception java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 randomly when getting an element.

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [ShaftHQ/SHAFT_ENGINE#1008]
Getting exception  java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 when getting an element randomly 

![image](https://user-images.githubusercontent.com/46620378/229234533-8175772d-956e-46a9-90f9-6b373da4780d.png)

`java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
 com.shaft.gui.element.internal.ElementActionsHelper.lambda$waitForElementPresence$0(ElementActionsHelper.java:214)
 org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
 com.shaft.gui.element.internal.ElementActionsHelper.waitForElementPresence(ElementActionsHelper.java:158)
 com.shaft.gui.element.internal.ElementActionsHelper.getMatchingElementsInformation(ElementActionsHelper.java:782)
 com.shaft.gui.element.internal.ElementActionsHelper.identifyUniqueElement(ElementActionsHelper.java:744)
 com.shaft.gui.element.internal.ElementActionsHelper.performActionAgainstUniqueElement(ElementActionsHelper.java:731)
 com.shaft.gui.element.internal.FluentElementActions.getText(FluentElementActions.java:604)
 de.vodafone.pages.DSL.DSL_Login.setCookie(DSL_Login.java:37)
 de.vodafone.tests.DSL.ST.ST_DSLSetup.setup(ST_DSLSetup.java:32)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.base/java.lang.reflect.Method.invoke(Method.java:568)
 org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
 org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
 org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
 org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
 org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
 org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
 org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
 org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
 org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
 org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
 org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
 org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
 java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
 org.testng.TestRunner.privateRun(TestRunner.java:829)
 org.testng.TestRunner.run(TestRunner.java:602)
 org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
 org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
 org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
 org.testng.SuiteRunner.run(SuiteRunner.java:330)
 org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
 org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
 org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
 org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
 org.testng.TestNG.runSuites(TestNG.java:1099)
 org.testng.TestNG.run(TestNG.java:1067)
 org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
 org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
 org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
 org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
 org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
 org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
 org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
 org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)`

**Comment by MohabMohie** [comment]
Is that reproducible on the main branch? I already fixed it but it's still there on the last release

**Comment by MahmoudElSharkawy** [comment]
> Is that reproducible on the main branch? I already fixed it but it's still there on the last release

I found this when I was doing some tests on web factory with the latest release.

**Comment by MohabMohie** [comment]
It's closely tied to firefox and safari... But it's already fixed on the main branch, so no worries there
