### ISSUE TITLE
[Bug]: org.openqa.selenium.StaleElementReferenceException: in waitToBeReady method

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [ShaftHQ/SHAFT_ENGINE#1017]
![image](https://user-images.githubusercontent.com/46620378/229609739-4ec7b0f4-c0b0-4dab-ade2-5d11b1aea649.png)

[Exception stacktrace](https://gist.github.com/MahmoudElSharkawy/741dbca6580fcc8e3b5dc1351de0a167)

 SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 7.2.20230403

**Comment by MohabMohie** [comment]
fixed by implementing the new nested action approach to get the element information and perform the `.isDisplayed()` call inside the fluent wait itself.
