### ISSUE TITLE
setRemoteDriverInstance error is displayed and the running cannot be completed

### ISSUE THREAD

**Issue by KarimanKhatab** [ShaftHQ/SHAFT_ENGINE#1026]
**Describe the bug**

am trying to run an android app . Set the mobile capabilities and Execution.
When running it , the app is already installed due to reading file path from the script but this error appears and the running is stopped
java.lang.AssertionError: Driver Factory Action "setRemoteDriverInstance" failed. With the following test data "Failed to instantiate remote driver instance.

![image](https://user-images.githubusercontent.com/95859408/229952070-f35cd6fd-4205-4641-8ac6-908161e0754c.png)

**Link to SHAFT_Engine Console logs**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ console logs, and link it here.
Do _NOT_ paste your full console logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include console logs!

**Link to SHAFT_Engine Extent Report HTML**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ extent report .html file, and link it here.

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 7.1.20230321
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS]  Android
 4. Desktop Browser (if applicable): [e.g. chrome, safari]
 5. Desktop Browser Version (if applicable): [e.g. 22]
 6. Mobile Device Name (if applicable): [e.g. iPhone6] device 1 "emulator"
 7. Mobile Device OS (if applicable): [e.g. iOS8.1] 11.0
 8. Mobile Device Browser or Native App:  Native
 9. Mobile Device Browser (if applicable): [e.g. chrome, safari] 
 10. Mobile Device Browser Version (if applicable): [e.g. 22]

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/95859408/229952080-533a8012-5628-4c71-80cc-acf90c73e2c7.png)

**Additional context**

Add any other relevant context about the problem here.

**Comment by MohabMohie** [comment]
Hello @KarimanKhatab , without filling the needed data we're unable to support you further.
Please attach the full stacktrace so that we can troubleshoot, and please note that a new release will be pushed today, you can start by upgrading to it.

**Comment by MohabMohie** [comment]
I will close the issue due to lack of response. Kindly upgrade to the latest release and feel free to reopen the issue if it's still there.
