### ISSUE TITLE
An error appears when trying to run the class or the test but when running it from maven test it is working fine

### ISSUE THREAD

**Issue by KarimanKhatab** [ShaftHQ/SHAFT_ENGINE#1041]
**Describe the bug**

I am just opening a mobile app using the last version of shaft engine **7.2.20230408** but when trying to run the class or the test find this error but when running it from maven test it is working okay , open the app and generating the two reports
![image](https://user-images.githubusercontent.com/95859408/230805342-629f5ebc-0f30-4852-9d21-5eb71df7f56e.png)

**Link to SHAFT_Engine Console logs**
**Exception in thread "main" org.testng.TestNGException: 
Cannot load class from file: io.github.shafthq.shaft.listeners.TestNGListener
	at org.testng.internal.ClassHelper.fileToClass(ClassHelper.java:301)
	at org.testng.TestNG.configure(TestNG.java:1513)
	at com.intellij.rt.testng.IDEARemoteTestNG.configure(IDEARemoteTestNG.java:33)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:108)
**
Create a [GIST](https://gist.github.com) which is a paste of your _full_ console logs, and link it here.
Do _NOT_ paste your full console logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include console logs!

**Link to SHAFT_Engine Extent Report HTML**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ extent report .html file, and link it here.

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): **7.2.20230408**
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable): 
 3. Desktop OS: [e.g. iOS] **Android**
 4. Desktop Browser (if applicable): [e.g. chrome, safari] **NA**
 5. Desktop Browser Version (if applicable): [e.g. 22] **NA**
 6. Mobile Device Name (if applicable): [e.g. iPhone6] **Android Emulator**
 7. Mobile Device OS (if applicable): [e.g. iOS8.1] 11.0
 8. Mobile Device Browser or Native App:  **Hybrid**
 9. Mobile Device Browser (if applicable): [e.g. chrome, safari] 
 10. Mobile Device Browser Version (if applicable): [e.g. 22]

**To Reproduce**

1. Go to '...' just set the capabilities "mobile capabilities, Execution capabilities"
2.
**The code**
public class RegistrationTest{
    private SHAFT.GUI.WebDriver driver;
    RegistrationPage registrationPage;

    @Test
    public void test(){
        System.out.print("test");
    }

   @BeforeMethod
 public void initBeforeTest(){
        System.setProperty("mobile_app", System.getProperty("testDataFolderPath")+"xxx.apk");
       driver = new SHAFT.GUI.WebDriver();
        registrationPage = new RegistrationPage(driver);
    }
    @AfterMethod
    public void closeApp(){
        DriverFactory.closeAllDrivers();
    }

**Expected behavior**

When running the class or the test the mobile app is opened in the simulator

**Actual behavior:**
The above error is displayed in the console and no running happened, and the success running happened when run from maven test only and generate the two reports

**Screenshots**

If applicable, add screenshots, gifs, or video recordings to help explain the issue you're facing.

**Additional context**

Add any other relevant context about the problem here.

**Comment by MohabMohie** [comment]
Please note that the name of the listener class has been reverted back to its original value. So it's no longer `io.github.shafthq.shaft.listeners.TestNGListener`

You can find the correct name in your pom.xml and on the readme.md footer of our getting started guide.

**Comment by KarimanKhatab** [comment]
@MohabMohie  working fine now after changing the listener , Thanks
