### ISSUE TITLE
[Bug]: Blocking issue whereby SHAFT overrides the cucumber properties file

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#1044]
https://shaft-engine.slack.com/archives/CTWG4AA0P/p1681136493953369

**Comment by martin397** [comment]
this Cucumber.properties class which should call the steps, connector packages to initiate the driver,
so the screenshot attached before 
![6A4CEEFC-1A55-4273-820D-F7E1D15499CF_1_105_c](https://user-images.githubusercontent.com/109524818/231130572-457ca910-a88e-4ced-b5e9-a57b766a6f40.jpeg)


after running the cucumber runner it's clear that cucumber.properties have been overwritten by the default properties file.


![EBDB287A-B4F7-4F2F-9F9E-27F19FB02D50](https://user-images.githubusercontent.com/109524818/231127497-96f2f5cc-1bb4-41de-9f17-9509006e2f42.jpeg)
![258B8FE1-EFFA-412F-BE1C-C258E4DDDC2B](https://user-images.githubusercontent.com/109524818/231127541-ff0ef182-50b2-4d5d-b01f-df21a57d0fb8.jpeg)
![E063DB92-A5D6-45D6-95E3-DFC0EE1170AC](https://user-images.githubusercontent.com/109524818/231127569-b8630aee-9177-44f0-9d4a-9e23a66229a1.jpeg)
![A22C38A0-9A40-4AEC-97A5-D1A9A1864CBD](https://user-images.githubusercontent.com/109524818/231127645-c9eed513-85aa-4285-aafe-349e92d0b22c.jpeg)
![AD1DC0A9-7E56-4770-B696-D4CBB28D9429](https://user-images.githubusercontent.com/109524818/231127745-8afbf630-0e40-457d-b9a0-8de480980563.jpeg)
