### ISSUE TITLE
[Bug]: SHAFT_ Reporting _ no screenshot added to allure report in case of "multiple elements found matching this locator" exception 

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#1052]
**Describe the bug**.
no screenshot added to allure report in case of "multiple elements found matching this locator" exception

**Link to SHAFT_Engine Console logs**
https://gist.github.com/zanoon2020/2bd483d32cf2a65702ca33d94d3d87dd

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):7.2.20230411  
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS]windows 10
 4. Desktop Browser (if applicable): [e.g. chrome, safari] all browsers

**To Reproduce**

1. in VisaulValidations.properties >  set screenshotParams_whenToTakeAScreenshot=ValidationPointsOnly
2. run any test that will fail due to multiple element found exception 

for exmaple 
```java
 public void test_ClickUsingJavaScript() {
        driver.browser().navigateToURL("https://www.saucedemo.com");
            driver.element().type( By.xpath("//input"), "standard_user")
}
```
**Actual behavior**
no screenshot attached at failed step in allure report 
failed step duplicated at allure report

**Expected behavior**

test will fail and screnshot from faluire will be attached to allure report as all other exceptions and step displayed one time not twice as appear in screenshot

**Screenshots**

If applicable, add screenshots, gifs, or video recordings to help explain the issue you're facing.
![image](https://user-images.githubusercontent.com/65794900/231572286-6081e8cd-7b2a-4dec-be56-fd8ade2debf8.png)

.

**Comment by zanoon2020** [comment]
@MohabMohie , screenshot added but new issue appeared 
the green mark and step log not appear 
![image](https://user-images.githubusercontent.com/65794900/231841878-b51884ed-7b48-4c62-bdb3-cf5b6e40abe6.png)

**Comment by MohabMohie** [comment]
Mmm... Would you share the code snippet to reproduce please?
It's working fine on the code you provided me with above... But I'm sure there are some uncovered cases.

**Comment by zanoon2020** [comment]
public void test_ClickUsingJavaScript() {
        driver.browser().navigateToURL("https://www.saucedemo.com");
            driver.element().type( By.xpath("//input"), "standard_user")
}

**Comment by MohabMohie** [comment]
That's exactly the same code I'm using...
😄 Now I feel lost...
Would you kindly delete your properties directory and try again on the branch that's linked to this issue?

**Comment by zanoon2020** [comment]
![image](https://user-images.githubusercontent.com/65794900/231871820-fad867d2-fd59-4596-b557-385419fdf823.png)
duplication error fixed but no screenshot 
new log
https://gist.github.com/zanoon2020/927df25868163f97c74983274952ec41

**Comment by zanoon2020** [comment]
@MohabMohie i will say weird , it works with type action and not working with click action

**Comment by MohabMohie** [comment]
okay... I refactored the entire element actions failure logic, and tested it with type and click, for multiple elements found, and for no such element exceptions.
would you take another look now please?
I added a couple of test classes... please feel free to add more test methods as you see fit to cover the cases you can identify.

**Comment by zanoon2020** [comment]
Dear @MohabMohie , sorry for late replay , kindly advice on how to test , i updated my fork and run my test but for some resaon i got same result . what i'm missing here 
![image](https://user-images.githubusercontent.com/65794900/232080443-424bd62e-a31f-4b57-a4f0-f54525aeb391.png)

**Comment by MohabMohie** [comment]
Please delete any local branches you have, and retest on the main branch.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
