### ISSUE TITLE
[Bug]: SHAFT_Properties_creating custom properties file not working as expected 

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#1073]
**Describe the bug**
i created custom properties file and placed it in the directory src/main/resources/properties/custom.properties 
but when running test **SHAFT used default ones** 

**Link to SHAFT_Engine Console logs**
https://gist.github.com/zanoon2020/92d423c8eb06b8dd6b62c8c0ba58eb8a

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 7.2.20230425  
 2.  Desktop OS: [e.g. iOS] Windows 10 
 3. Desktop Browser (if applicable): [e.g. chrome, safari] not related to browser 

**To Reproduce**

1. create custom.properties file and place it in the directory src/main/resources/properties/custom.properties 
2. run any test 
3. observe that not all properties read from the the file and shaft used default ones 

**Expected behavior**

SHAFT must take properties from file before default as per documentation 

**Screenshots**

![image](https://user-images.githubusercontent.com/65794900/234623718-3e38c2d6-f461-4d7c-827f-bab0bffb5b14.png)

**Additional context**

you can use these properties as an example 
targetBrowserName=MicrosoftEdge
forceCheckNavigationWasSuccessful=true

**Comment by MohabMohie** [comment]
fixed, thanks again for the excellent catch.
![image](https://user-images.githubusercontent.com/19201898/234845348-701cc79c-331f-4956-98a9-0b1a4097fec9.png)
