### ISSUE TITLE
[Bug]: SHAFT_Reporting_all steps executed after assertThat().text() not reported in allure report

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#1092]
**Describe the bug**

all steps executed after assertThat().text() not reported in allure report except verification steps 

**Link to SHAFT_Engine Console logs**
https://gist.github.com/zanoon2020/f7f34b1dc6531c216f65eaed8e8f5aa8

**Link to SHAFT_Engine Extent Report HTML**

https://gist.github.com/zanoon2020/d862632f3944f40d26952a21fe93e6be

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 0503
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS] win 10 
 4. Desktop Browser (if applicable): [e.g. chrome, safari]not related to browser 

**To Reproduce**

1. run the below test 
2. observe the allure report 

```java
@Test 
public void test_ClickUsingJavaScript() {
        driver.browser().navigateToURL("https://www.saucedemo.com");
        driver.element().assertThat(By.xpath("//div[@id='login_credentials']//h4")).text().equalsIgnoringCaseSensitivity("Accepted usernames are:").perform();
        driver.element().type(emailField, "standard_user")
                .type(passwordField, "secret_sauce")
                .clickUsingJavascript(loginButton)
                .clickUsingJavascript(product1)
                .clickUsingJavascript(shoppingCartButton)
                .verifyThat(productName).text().isEqualTo("Sauce Labs Backpack").perform();
    }
```
**Expected behavior**

all steps reported in allure report as usual 

**Screenshots**
execution log screenshot
![Screenshot 2023-05-04 161438](https://user-images.githubusercontent.com/65794900/236219984-47d7c85e-768a-42f7-8ac0-132719fdcc36.png)

allure report screenshot
![Screenshot 2023-05-04 161503](https://user-images.githubusercontent.com/65794900/236219997-e1cfbc01-3204-4709-9668-36758224dd9b.png)

**Comment by MohabMohie** [comment]
nice catch!

**Comment by zanoon2020** [comment]
verification pass
