### ISSUE TITLE
[Bug]: SHAFT_Reporting_AssertThat and verifyThat not logged in allure report

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#1160]
**Describe the bug**
assert that and verify that not logged in allure report 

**Link to SHAFT_Engine Console logs**
https://gist.github.com/zanoon2020/2bca418a49591205fdf68764ae3e92ec

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): v7.2.20230611
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable): **v7.2.20230503**

**To Reproduce**

1. Run any test that has verify step or assert
2. open allure report 
3. observe there is no verification step in allure report 

**Expected behavior**
verify step logged in allure report as usual 

**Screenshots**
actual result : 
![Screenshot 2023-06-11 155411](https://github.com/ShaftHQ/SHAFT_ENGINE/assets/65794900/f2db1bb1-892c-4c88-a76a-634b09af36d6)

expected results 

![Screenshot 2023-06-11 160123](https://github.com/ShaftHQ/SHAFT_ENGINE/assets/65794900/ab1ccc0c-46d8-4cc0-bb65-95aac48e5c73)

**Additional context**

Add any other relevant context about the problem here.

**Comment by zanoon2020** [comment]
as a start we can investigate profiles section in pom xml , after removing this part and constructing old POM.xml all works fine

**Comment by MohabMohie** [comment]
@zanoon2020 please note that this issue is not reproducible inside the engine project
<img width="1096" alt="image" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/19201898/a07c3687-e5d4-4f45-92e5-7c357b135de5">

how are you reproducing it? can you tell me more about the project setup? is this the core engine or a project that's using it?

**Comment by zanoon2020** [comment]
@MohabMohie  i think you have already solved it when you restructured the Profile part in POM.xml
