### ISSUE TITLE
[Bug]: Cannot edit the "fullReset" mobile capability 

### ISSUE THREAD

**Issue by Ayman-Alsahli** [ShaftHQ/SHAFT_ENGINE#1174]
**Describe the bug**

I am trying to set the fullReset mobile capability to false but it is getting ignored and it is always set to true when running the test causing the app to get uninstalled.

**Environment**

 SHAFT_Engine version: 7.2.20230611
 Mobile Device OS: Android 11
 Mobile Device Browser or Native App: Native app

**To Reproduce**

- Set the mobile capability "fullReset" to false in your properties file
- Run the test and check the value of the "fullReset" in the console logs

<img width="1919" alt="Screenshot 2023-06-20 at 9 32 03 PM" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/97877038/c9892491-0541-404c-83b6-73a321df12de">

**Comment by MohabMohie** [comment]
I apologize, but this issue seems to have been fixed as a byproduct of fixing that issue #1175

**Comment by Ayman-Alsahli** [comment]
that is fine. when this fix is expected to be released?

Thanks for your efforts

**Comment by MohabMohie** [comment]
an hour or so :)
