### ISSUE TITLE
[Bug]: Extent-report is not generated in case of using JUnit

### ISSUE THREAD

**Issue by roaamagdy** [ShaftHQ/SHAFT_ENGINE#1179]
After the run, `extent-reports` folder is always empty

**Comment by MohabMohie** [comment]
Hi @roaamagdy ,
Please note that extent report is currently not supported with JUnit.
I believe that we don't want to proceed with extent as we will be replacing it with out Summary report as the new lightweight single html file.

@MahmoudElSharkawy to advise if we have plans to widen extent support or to sunset it and please feel free to reopen the issue accordingly as a new feature request.
