### ISSUE TITLE
I cant find "bundleId"  , When I try to set data to "Mobile" properly file

### ISSUE THREAD

**Issue by elnagar1** [ShaftHQ/SHAFT_ENGINE#1226]
package com.shaft.properties.internal;

import com.shaft.tools.io.ReportManager;
import io.appium.java_client.remote.AutomationName;
import org.aeonbits.owner.Config.Sources;
import org.aeonbits.owner.ConfigFactory;

@SuppressWarnings("unused")
@Sources({"system:properties",
        "file:src/main/resources/properties/MobileCapabilities.properties",
        "file:src/main/resources/properties/default/MobileCapabilities.properties",
        "classpath:MobileCapabilities.properties",
})
public interface Mobile extends EngineProperties {
    @Key("selfManaged")
    @DefaultValue("false")
    boolean selfManaged();

    @Key("selfManagedAndroidSDKVersion")
    @DefaultValue("31")
    int selfManagedAndroidSDKVersion();

    @Key("mobile_platformName")
    @DefaultValue("")
    String platformName();

    @Key("mobile_platformVersion")
    @DefaultValue("")
    String platformVersion();

    @Key("mobile_deviceName")
    @DefaultValue("")
    String deviceName();

    @Key("mobile_automationName")
    @DefaultValue(AutomationName.ANDROID_UIAUTOMATOR2)
    String automationName();

    @Key("mobile_udid")
    @DefaultValue("")
    String udid();

    @Key("mobile_browserName")
    @DefaultValue("")
    String browserName();

    @Key("MobileBrowserVersion")
    @DefaultValue("")
    String browserVersion();

    @Key("mobile_app")
    @DefaultValue("")
    String app();

    @Key("mobile_appPackage")
    @DefaultValue("")
    String appPackage();

    @Key("mobile_appActivity")
    @DefaultValue("")
    String appActivity();

    private static void setProperty(String key, String value) {
        var updatedProps = new java.util.Properties();
        updatedProps.setProperty(key, value);
        Properties.mobile = ConfigFactory.create(Mobile.class, updatedProps);
        // temporarily set the system property to support hybrid read/write mode
        System.setProperty(key, value);
        ReportManager.logDiscrete("Setting \"" + key + "\" property with \"" + value + "\".");
    }

    default SetProperty set() {
        return new SetProperty();
    }

    class SetProperty implements EngineProperties.SetProperty {

        public SetProperty selfManagedAndroidSDKVersion(int value) {
            setProperty("selfManagedAndroidSDKVersion", String.valueOf(value));
            return this;
        }

        public SetProperty selfManaged(boolean value) {
            setProperty("selfManaged", String.valueOf(value));
            return this;
        }

        public SetProperty platformName(String value) {
            setProperty("mobile_platformName", value);
            return this;
        }

        public SetProperty platformVersion(String value) {
            setProperty("mobile_platformVersion", value);
            return this;
        }

        public SetProperty deviceName(String value) {
            setProperty("mobile_deviceName", value);
            return this;
        }

        /**
         * @param value io.appium.java_client.remote.AutomationName
         */
        public SetProperty automationName(String value) {
            setProperty("mobile_automationName", value);
            return this;
        }

        public SetProperty udid(String value) {
            setProperty("mobile_udid", value);
            return this;
        }

        public SetProperty browserName(String value) {
            setProperty("mobile_browserName", value);
            return this;
        }

        public SetProperty browserVersion(String value) {
            setProperty("MobileBrowserVersion", value);
            return this;
        }

        public SetProperty app(String value) {
            setProperty("mobile_app", value);
            return this;
        }

        public SetProperty appPackage(String value) {
            setProperty("mobile_appPackage", value);
            return this;
        }

        public SetProperty appActivity(String value) {
            setProperty("mobile_appActivity", value);
            return this;
        }
    }
}

**Comment by MohabMohie** [comment]
Kindly find the full list of built-in properties here:
https://shafthq.github.io/docs/Properties/PropertiesList#mobile

And please note that description
<img width="203" alt="image" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/19201898/1154b905-b62a-49b2-afa2-e02d0013d798">

This means that you can use mobile_bundleId in your custom properties file, via CLI, or you can even use ```java System.setProperty("mobile_bundleId", "");``` if you want to configure it in your code.

The same is applicable for any/all other [appium capabilities](https://appium.io/docs/en/2.0/guides/caps/)
