### ISSUE TITLE
[Bug]: unexpected content type for Multi-parted API calls

### ISSUE THREAD

**Issue by ShalabyMusala** [ShaftHQ/SHAFT_ENGINE#1229]
**Describe the bug**

Am trying to do some api testing 
and i have an api endpoint that takes two request parts
one is file and the other is a JSON object

When sending the request using the normal code flow ;

```
List<List<Object>> params = new ArrayList<>();
params.add(Arrays.asList("request", jsonInput.toString()));
params.add(Arrays.asList("file", file));

 return api
                .post("/endpoint-uri")
                .setContentType(ContentType.MULTIPART)
                .setParameters(params, ParametersType.FORM)
```

am having error 500 on the api level as the following "Content type 'text/plain;charset=US-ASCII' not supported"

so somehow the content type is been overridden to text/plain and am not sure from where exactly that content type is been set

 
**Link to SHAFT_Engine Console logs**

[GIST](https://gist.github.com/ShalabyMusala/ca28b37a465981f34ccbf3a07116d3aa)

**Environment**

- SHAFT_Engine version (7.2.20230621)
- Desktop OS: Ubuntu 22.04
- Desktop Browser: chrome

**Comment by MohabMohie** [comment]
please note that this issue is not reproducible on our side, kindly provide us with code that helps to reproduce the issue.
as an extra mile, you can also provide us with a native rest assured code snippet that works as expected so that we can study and implement the proper fix.

**Comment by ShalabyMusala** [comment]
> please note that this issue is not reproducible on our side, kindly provide us with code that helps to reproduce the issue. as an extra mile, you can also provide us with a native rest assured code snippet that works as expected so that we can study and implement the proper fix.

I have done the same request using rest assured given the below code;
```
  RestAssuredConfig config = RestAssured
                        .config()
                        .encoderConfig(EncoderConfig.encoderConfig().defaultContentCharset("UTF-8"));

  Response response = RestAssured.given()
                        .header("Authorization", token)
                        .config(config)
                        .multiPart("file", file)
                        .multiPart("request", jsonInput.toString(), "application/json")
                        .contentType("multipart/form-data")
                        .post("/endpoint-uri");

                        
        System.out.println(response.getStatusCode());
```

and the response code is 200


for the code nothing is special; the endpoint we are testing is like

```
   @PostMapping("/")
    public void controllerMethod(
            @RequestPart("file") MultipartFile file,
            @RequestPart("request") CustomClass request) {
    }
```

**Comment by MohabMohie** [comment]
@ShalabyMusala apologies for the belated response. but please note that we were still not able to reproduce this issue.

Kindly provide us with a working block of code that we can use to reproduce, fix, and test the issue.

PS: feel free to reopen this issue when/if you wish to provide us with the executable block of code
