### ISSUE TITLE
[Bug]: Null Pointer Exception keeps popping up randomly while running test execution 

### ISSUE THREAD

**Issue by ieZaky** [ShaftHQ/SHAFT_ENGINE#1255]
While running test execution for a certain website specific to work, I noticed this error "java.lang.NullPointerException" that keeps popping up in the logs. I use specific proxy settings regarding work and I set the new flag driverProxySettings=false.  
Note: Execution runs normally ignoring this error but it keeps popping up a lot so I wanted to report it.
**SHAFT_Engine Console logs**
[ERROR] java.lang.NullPointerException: Cannot invoke "com.shaft.gui.internal.image.AnimatedGifManager.writeToSequence(java.awt.image.RenderedImage)" because the return value of "java.lang.ThreadLocal.get()" is null
com.shaft.gui.internal.image.ScreenshotManager.appendToAnimatedGif(ScreenshotManager.java:646)
com.shaft.gui.internal.image.ScreenshotManager.startOrAppendToAnimatedGif(ScreenshotManager.java:634)
com.shaft.gui.internal.image.ScreenshotManager.internalCaptureScreenShot(ScreenshotManager.java:392)
com.shaft.gui.internal.image.ScreenshotManager.captureScreenShot(ScreenshotManager.java:137)
com.shaft.gui.element.internal.ElementActionsHelper.takeScreenshot(ElementActionsHelper.java:593)
com.shaft.gui.element.internal.ElementActionsHelper.createReportAttachments(ElementActionsHelper.java:1057)
com.shaft.gui.element.internal.ElementActionsHelper.reportActionResult(ElementActionsHelper.java:1095)
com.shaft.gui.element.internal.ElementActionsHelper.passAction(ElementActionsHelper.java:924)
com.shaft.gui.element.internal.FluentElementActions.getText(FluentElementActions.java:572)
com.shaft.validation.internal.ValidationsHelper.validateElementAttribute(ValidationsHelper.java:152)
com.shaft.validation.internal.ValidationsExecutor.performValidation(ValidationsExecutor.java:166)
com.shaft.validation.internal.ValidationsExecutor.perform(ValidationsExecutor.java:148)
de.vodafone.pages.eCare.Dashboard.validateNotificationBoxExist(Dashboard.java:144)
de.vodafone.tests.eCare.ST.WFGT_208.GC03(WFGT_208.java:29)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
org.testng.TestRunner.privateRun(TestRunner.java:848)
org.testng.TestRunner.run(TestRunner.java:621)
org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
org.testng.SuiteRunner.run(SuiteRunner.java:336)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
org.testng.TestNG.runSuites(TestNG.java:1114)
org.testng.TestNG.run(TestNG.java:1082)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105) | com.shaft.tools.io.ReportManager - main - 03:38:05 PM 

<img width="863" alt="image" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/49809725/07190271-c116-43b5-a393-c35fe127bfe5">

**Environment**

 1. SHAFT_Engine version: 7.3.20230824.1
 3. Desktop OS: Windows
 4. Desktop Browser (if applicable): Firefox
 5. Desktop Browser Version (if applicable): 116.0.3

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy since you own this feature

**Comment by MohabMohie** [comment]
@ieZaky thank you for the report, upon further investigation this looks related to the Animated GIF Manager.
As a workaround you are kindly asked to disable animated GIF creation until the issue is troubleshooted and resolved.
PS. Animated GIF generation has a high performance impact and is therefore disabled by default.

**Comment by MohabMohie** [comment]
blind fix will be rolled out on the next release.

**Comment by ieZaky** [comment]
Thanks a lot for your support @MohabMohie
