### ISSUE TITLE
[Bug]: Summary reports are generated 3 times on ci (Junit tests)

### ISSUE THREAD

**Issue by roaamagdy** [ShaftHQ/SHAFT_ENGINE#1280]
- When running junit tests on ci, summary reports are generated 3 times.
- All reports have the same results but different execution time and total validations cases.

**Comment by MahmoudElSharkawy** [comment]
Can you please share some logs to be able to investigate more?

**Comment by roaamagdy** [comment]
@MahmoudElSharkawy . Sharing logs will be hard as I don't know which part is executed 3 times.

https://shaft-engine.slack.com/archives/CTWG4AA0P/p1693908900484429

**Comment by MahmoudElSharkawy** [comment]
@roaamagdy  So, What I learned from the conversation on slack is that you have custom listener and integration with Spring framework, did I understand correctly?

**Comment by roaamagdy** [comment]
@MahmoudElSharkawy no I don't have custom listener, I am using JunitListener of shaft
