### ISSUE TITLE
[Bug]: The actual Download folder path is not as the path in the properties file

### ISSUE THREAD

**Issue by ahmedtalaat-8** [ShaftHQ/SHAFT_ENGINE#1299]
we was working with the SHAFT version 7.2.20230408 and the download folder path in the property file was "target/downloadedFiles/" and when we download a file using SHAFT it was downloaded in " src/test/resources/TestDataFiles/target/downloadedFiles " which was ok while running our tests locally or on the pipeline because the file is downloaded in the project's file.
After upgrading SHAFT to the latest version i found out that the files are downloaded in the windows "Downloads" file , so how can i change the the download file path because i tried to change it from the property file but it stills the same.

**Comment by MohabMohie** [comment]
Which version had this bug?

**Comment by ahmedtalaat-8** [comment]
7.3.20230829
