### ISSUE TITLE
[Bug]: Screenshot method is not working well 

### ISSUE THREAD

**Issue by SondosSaber** [ShaftHQ/SHAFT_ENGINE#1354]
**Describe the bug**

In a TC while we are making validation on some exisitng info in the modal, the method that caputre the screenshot of the validations, is clicking on the app screen so the modal is being got closed and then the rest of validation failues due to the non-exisitng of the rest of elements

**Link to SHAFT_Engine Console logs**
SHAFT Engine Logs - Current Method log: init

[ReportManager] Setting "targetOperatingSystem" property with "windows". @05-11-2023 13:01:47.0995 PM
[ReportManager] Capabilities {acceptInsecureCerts: true, browserName: MicrosoftEdge, ms:edgeOptions: {args: [--start-maximized, --remote-allow-origins=*, --enable-automation, --disable-background-timer-..., --disable-backgrounding-occ..., --disable-features=Calculat..., --disable-hang-monitor, --disable-domain-reliability, --disable-renderer-backgrou..., --disable-features=Autofill..., --metrics-recording-only, --no-first-run, --no-default-browser-check, --silent-debugger-extension..., --disable-extensions, --disable-component-extensi..., --disable-dev-shm-usage, --disable-features=MediaRouter, --disable-features=Translate, --disable-ipc-flooding-prot..., --disable-background-networ..., --mute-audio, --disable-breakpad, --ignore-certificate-errors, --disable-device-discovery-..., --force-color-profile=srgb, --hide-scrollbars, --host-resolver-rules, --no-pings, --disable-features=AvoidUnn..., --disable-features=Certific..., --disable-sync, --disable-features=Optimiza..., --disable-features=DialMedi..., --disable-features=GlobalMe..., --disable-features=Improved..., --disable-features=LazyFram..., --disable-field-trial-config, --enable-features=NetworkSe..., --enable-features=NetworkSe..., --enable-use-zoom-for-dsf, --log-net-log, --net-log-capture-mode, --disable-client-side-phish..., --disable-default-apps, --disable-features=Interest...], extensions: [], prefs: {download.default_directory: C:\Sondos\CIT\R10\RefAppAut..., download.prompt_for_download: false, profile.default_content_settings.popups: 0}}, pageLoadStrategy: none, timeouts: {pageLoad: 60000, script: 30000}, unhandledPromptBehavior: ignore, webSocketUrl: true} @05-11-2023 13:01:48.0037 PM
[ReportManager] Attempting to run locally on: "windows | Microsoft edge". @05-11-2023 13:01:48.0039 PM
[ReportManager] Identifying OS/Driver combination. Please note that if a new browser/driver executable will be downloaded it may take some time depending on your connection... @05-11-2023 13:01:48.0041 PM
[ReportManager] Successfully Opened: "windows | Microsoft edge". @05-11-2023 13:01:53.0124 PM
[ReportManager] Target URL: "https://vfgrp-app2-test.app-prod.digitalretail.vodafone.com/" @05-11-2023 13:01:53.0201 PM
[ReportManager] Initial URL: "about:blank" @05-11-2023 13:01:53.0234 PM
[ReportManager] Navigate to url "https://vfgrp-app2-test.app-prod.digitalretail.vodafone.com/". @05-11-2023 13:02:00.0557 PM
[ReportManager] Explicit wait until: "url to contain "https://vfgrp-app". Current url: "https://vfgrp-app2-test.app-prod.digitalretail.vodafone.com/"". @05-11-2023 13:02:00.0569 PM

SHAFT Engine Logs - Current Method log: setup

[ReportManager] File Action "DoesFileExist" successfully performed. With the following test data "File Path: "src/test/resources/changePlanJourneyTestData/planFeatureData.json"". @05-11-2023 13:02:00.0691 PM
[ReportManager] File Action "GetAbsolutePath" successfully performed. With the following test data "Relative Folder Path: "src/test/resources/changePlanJourneyTestData/planFeatureData.json"". @05-11-2023 13:02:00.0692 PM
[ReportManager] File Action "DoesFileExist" successfully performed. With the following test data "File Path: "src/test/resources/changePlanJourneyTestData/planFeatureData.json"". @05-11-2023 13:02:02.0393 PM
[ReportManager] File Action "GetAbsolutePath" successfully performed. With the following test data "Relative Folder Path: "src/test/resources/changePlanJourneyTestData/planFeatureData.json"". @05-11-2023 13:02:02.0393 PM

SHAFT Engine Logs - Current Method log:

[0;7m------------------------------------------------------------------------------------------------------------------------------------------------
                                        Starting Execution: '1 out of 1' test cases in the current suite                                        
     Test Method: 'changePlanJourney.planStepFeature.ALPlanStepTests.validatePlanDetailsIsDisplayedOnceClickingOnSeeMoreDetailsButtonForPM'     
     Test Description: 'PM || Plan Step || Google Chrome || Ensure that plan details is displayed once clicking on See more details button'     
------------------------------------------------------------------------------------------------------------------------------------------------
[0m
[ReportManager] Type "6947826024" into "MSISDN". @05-11-2023 13:02:02.0772 PM
[ReportManager] Setting "skipTestsWithLinkedIssues" property with "true". @05-11-2023 13:02:03.0076 PM
[ReportManager] Select "PAYM" from "Plan Type". @05-11-2023 13:02:03.0400 PM
[ReportManager] Moved the mouse to the middle of the element. @05-11-2023 13:02:03.0611 PM
[ReportManager] Click "Continue". @05-11-2023 13:02:03.0677 PM
[ReportManager] Moved the mouse to the middle of the element. @05-11-2023 13:02:03.0911 PM
[ReportManager] Click "Continue Without Code". @05-11-2023 13:02:03.0952 PM
[ReportManager] Moved the mouse to the middle of the element. @05-11-2023 13:02:05.0977 PM
[ReportManager] Click "See more details". @05-11-2023 13:02:06.0057 PM
[ReportManager] Assertion "ValidateElementExists" PASSED. Expected "Element Should Exist, locator 'By.xpath: //h2[@data-testid='plan-details-subtitle']'" and Actual "Element Exists". Comparison Type "EQUALS". Validation Type "POSITIVE". @05-11-2023 13:02:09.0423 PM
[ReportManager] Assertion Passed: The Element located by "By.xpath: //h2[@data-testid='plan-details-subtitle']" exists. @05-11-2023 13:02:09.0423 PM
[ReportManager] Successfully created attachment 'Screenshot - 1699182128491_validatePlanDetailsIsDisplayedOnceClickingOnSeeMoreDetailsButtonForPM_ValidateElementExists_passed' @05-11-2023 13:02:09.0457 PM
[ReportManager] Expected condition failed: waiting for com.shaft.gui.element.internal.ElementActionsHelper$$Lambda$1076/0x00000008012aa110@4b3ebc09 (tried for 60 second(s) with 100 milliseconds interval) || no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-testid='plan-details-name']"} @05-11-2023 13:03:09.0516 PM
[ReportManager] Assertion "ValidateElementExists" FAILED. Expected "Element Should Exist, locator 'By.xpath: //div[@data-testid='plan-details-name']'" and Actual "Element Doesn't Exists". Comparison Type "EQUALS". Validation Type "POSITIVE". @05-11-2023 13:03:10.0075 PM
[ReportManager] Assertion Failed: The Element located by "By.xpath: //div[@data-testid='plan-details-name']" exists. @05-11-2023 13:03:10.0077 PM
[ReportManager] Successfully created attachment 'Screenshot - 1699182189735_validatePlanDetailsIsDisplayedOnceClickingOnSeeMoreDetailsButtonForPM_ValidateElementExists_failed' @05-11-2023 13:03:10.0078 PM
[ReportManager] Successfully created attachment 'Validation Test Data - Failure Reason' @05-11-2023 13:03:10.0081 PM
[ReportManager] Assertion "ValidateElementExists" FAILED. Expected "Element Should Exist, locator 'By.xpath: //div[@data-testid='plan-details-name']'" and Actual "Element Doesn't Exists". Comparison Type "EQUALS". Validation Type "POSITIVE". @05-11-2023 13:03:10.0082 PM
[ReportManager] Successfully created attachment 'SHAFT Engine Logs - Current Method log: init' @05-11-2023 13:03:10.0095 PM
[ReportManager] Successfully created attachment 'SHAFT Engine Logs - Current Method log: setup' @05-11-2023 13:03:10.0097 PM

**Environment**
Chrome, edge

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):  7.4.20231026
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS] windows
 4. Desktop Browser (if applicable): [e.g. chrome, safari] chrome, edge
 5. Desktop Browser Version (if applicable): [e.g. 22] chrome [118.0.5993.120 ] edge [118.0.2088.76 ]
 6. Mobile Device Name (if applicable): [e.g. iPhone6]
 7. Mobile Device OS (if applicable): [e.g. iOS8.1]
 8. Mobile Device Browser or Native App: 
 9. Mobile Device Browser (if applicable): [e.g. chrome, safari]
 10. Mobile Device Browser Version (if applicable): [e.g. 22]

**To Reproduce**

**Expected behavior**

**Screenshots**

If applicable, add screenshots, gifs, or video recordings to help explain the issue you're facing.

**Additional context**

Add any other relevant context about the problem here.

**Comment by MohabMohie** [comment]
@SondosSaber after several attempts I wasn't able to reproduce this issue.
Kindly provide a code snippet `@Test` method that I can copy-paste in my test classes to reproduce this problem and attempt fixing it.

PS. I recommend setting the `screenshotParams_screenshotType` to `Regular` and trying again.
PSS. feel free to reopen once you can share a code snippet to reproduce the issue. I will attempt a blind fix anyway.

**Comment by SondosSaber** [comment]
@MohabMohie 
hello Mohab 
  
    @Test
    public void validatePlanDetailsIsDisplayedOnceClickingOnSeeMoreDetailsButtonForPM(){
        new EntryPointPage(driver)
                .setCustomerData_AL_PMAndNavigateToPromoCodePage(validNumberPM)
                .navigateToCurrentPlanPageWithoutPromoCode()
                .openSeeMoreDetailsPlanModal();

        Validations.assertThat().element(PlanPage.planDetailsTitle_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planName_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planOriginalPrice_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planOriginalPriceCurrency_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planFinalPrice_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planFinalPriceCurrency_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.recurrentPayment_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.duration_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.firstInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.secondInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.thirdInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.fourthInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.closeIcon_Modal()).isEnabled().perform();
        Validations.assertThat().element(PlanPage.chooseThisPlanBtn_Modal()).isEnabled().perform();
         Validations.assertThat().element(PlanPage.closeBtn_Modal()).isEnabled().perform();
    }
    
    After the first validation and upon making the screenshot of the first validation the tooltip/modal is closed as it is closing by clicking outside it, rest of validations are getting failed as the modal is closed.
    
    by this workaround the code is working

    @Test
    public void validatePlanDetailsIsDisplayedOnceClickingOnSeeMoreDetailsButtonForPM(){
        new EntryPointPage(driver)
                .setCustomerData_AL_PMAndNavigateToPromoCodePage(validNumberPM)
                .navigateToCurrentPlanPageWithoutPromoCode()
                .openSeeMoreDetailsPlanModal();

        SHAFT.Properties.visuals.set().screenshotParamsWhenToTakeAScreenshot("FailuresOnly");
        Validations.assertThat().element(PlanPage.planDetailsTitle_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planName_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planOriginalPrice_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planOriginalPriceCurrency_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planFinalPrice_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.planFinalPriceCurrency_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.recurrentPayment_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.duration_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.firstInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.secondInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.thirdInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.fourthInclusion_Modal()).exists().perform();
        Validations.assertThat().element(PlanPage.closeIcon_Modal()).isEnabled().perform();
        Validations.assertThat().element(PlanPage.chooseThisPlanBtn_Modal()).isEnabled().perform();
        SHAFT.Properties.visuals.set().screenshotParamsWhenToTakeAScreenshot("ValidationPointsOnly");
        Validations.assertThat().element(PlanPage.closeBtn_Modal()).isEnabled().perform();
    }
