### ISSUE TITLE
[Bug]: API tests reporting does not log the response headers

### ISSUE THREAD

**Issue by andinica-idea** [ShaftHQ/SHAFT_ENGINE#1564]
**Describe the bug**

When running API tests using the SHAFT framework, the Allure report does not log the response headers of requests calls. 
A workaround to this would be to use the following line of code: 
Allure.addAttachment("API Response - Headers", String.valueOf(response.getHeaders()));
But this adds the "API Response - Headers" outside of the test method logging, not inside it. You can see how this looks like in the below screenshot.

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 8.1.20240324

**To Reproduce**

1. Wrap the following code in a test method
`response =
                    rst.buildNewRequest(path, RestActions.RequestType.GET)
                            .useRelaxedHTTPSValidation()
                            .setParameters(queryParams, RestActions.ParametersType.QUERY)
                            .setTargetStatusCode(statusCode)
                            .performRequest()
                            .thenReturn();`
2. Run the test 
3. Open the report and go to the request details part of the report

**Expected behavior**

Report contains the following sections: API Request - Specifications (which contains the request initial headers), API Response - JSON Body and a section where you can see the API Response - Headers.

**Actual behavior**

Report only contains API Request - Specifications and API Response - JSON Body

**Screenshots**

The screenshot from below contains API Response - Headers because I added this line of code in the test method:
Allure.addAttachment("API Response - Headers", String.valueOf(response.getHeaders()));
![Screenshot 2024-03-28 at 11 03 43](https://github.com/ShaftHQ/SHAFT_ENGINE/assets/139343329/e4732f79-3e29-4370-8779-1d87d9394dcb)

Screenshot from below does not contains API Response - Headers because the .addAttachemnt call was not included.
![Screenshot 2024-03-28 at 14 33 48](https://github.com/ShaftHQ/SHAFT_ENGINE/assets/139343329/bf9d5c09-8816-4240-ae30-17cba8ef2b0b)

**Comment by MohabMohie** [comment]
will now include full information for request and response
<img width="694" alt="image" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/19201898/95d53544-9d53-460b-8cde-dd9a6b770e67">

<img width="1257" alt="image" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/19201898/eab2a271-b038-4e1d-b0fc-1b8ae0e4551e">

<img width="1259" alt="image" src="https://github.com/ShaftHQ/SHAFT_ENGINE/assets/19201898/885b51b0-c970-43b4-8747-5a225a74552e">
