### ISSUE TITLE
[Feature Request]: Request to customize Allure Reports with Company Logo and Update report title

### ISSUE THREAD

**Issue by SayyedaNousheen** [ShaftHQ/SHAFT_ENGINE#1566]
**Problem:**
We have a requirement to update our company logo in the test execution results
It would be great if allure reports can be customisable 

 **Solution Requirement:**
For every test run, company logo should be updated instead of Shaft Logo
Report title can be "Execution Summary Report" instead of "Allure Report"

**Reports to be updated:**
1. Execution Summary Folder -> Execution summary report
2. allure-reports -> index.html

**Comment by MohabMohie** [comment]
note to self, explore the possibility of using a custom plugin: https://github.com/allure-framework/allure-docs/blob/main/content/plugins/overview.md#step-4-adding-a-new-widget-on-the-overview-page
