### ISSUE TITLE
[Bug]: User Added Options are not working properly

### ISSUE THREAD

**Issue by MustafaAgamy** [ShaftHQ/SHAFT_ENGINE#1598]
**Describe the bug**

The "Enable BiDi" flag  is opening new tab which is creating conflicts with added options

**Link to SHAFT_Engine Console logs**

 [Console logs link](https://gist.github.com/d141e06ca7048082a94539f7e0733389.git) 

**Link to SHAFT_Engine Extent Report HTML**

N/A

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):[8.2.20240411]
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS] Windows
 4. Desktop Browser (if applicable): [e.g. chrome, safari] Chrome/Edge
 5. Desktop Browser Version (if applicable): [e.g. 22] N/A

**To Reproduce**

1. Add this code to your SHAFT setup code :
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--incognito");
        driver.set(new SHAFT.GUI.WebDriver(DriverFactory.DriverType.CHROME, options));
2. Launch the Test

**Expected behavior**

The custom added options to your Driver should be added successfully

**Screenshots**

[Bug Video.webm](https://github.com/ShaftHQ/SHAFT_ENGINE/assets/117293921/7c4f57e6-058a-4fe4-89ea-72ee3c510e94)

**Additional context**

This bug can be fixed by setting the Enable BiDi flag to false which won't open the BiDi Mapper Tab which will remove the conflict

**Comment by MohabMohie** [comment]
the user can be advised to disable BiDi since this flag is configurable. there is no need to treat this as a SHAFT bug since it is the expected behavior for Selenium WebDriver.
