### ISSUE TITLE
[Bug]: Query params are not added to requests that also have a body

### ISSUE THREAD

**Issue by andinica-idea** [ShaftHQ/SHAFT_ENGINE#1615]
**Describe the bug**

When trying to send a PUT/POST request using SHAFT's Request builder query params are not added to the request if the request also has a body.
If the request does not have a body, then query params are added.

**To Reproduce**

1. Build a POST/PUT request with anything in the body (but not null) and some query params (again, not null)
2. Send the request

**Expected behavior**

Request is sent with both body and query params.

**Actual behavior**
Request is sent only with body.

**Comment by MohabMohie** [comment]
Can you share a snippet of native code that's working for you dear? 
Usually only one of the three is used. Form parameters, query parameters or body. So this was actually by design from our side and not a bug 
But if we understand the reasoning we can enhance it
