### ISSUE TITLE
[Bug]: No Appium session started for most recent SHAFT version

### ISSUE THREAD

**Issue by rsaveanu-salt** [ShaftHQ/SHAFT_ENGINE#1638]
**Describe the bug**

When running an automated test on a real mobile device locally or in grid, no Appium session is created: confirmed by the Appium logs.

**Link to SHAFT_Engine Console logs**

`[INFO] Setting discrete logging to: 'false' | com.shaft.tools.io.ReportManager - main - 05:28:29 PM 
[INFO] Initializing the WebDriver. | salt.bank.automation.tests.mobile.MobileDriver - main - 05:28:29 PM 
[INFO] Setting "autoMaximizeBrowserWindow" property with "false". | com.shaft.tools.io.ReportManager - main - 05:28:29 PM 
[INFO] Setting "screenshotParams_screenshotType" property with "VIEWPORT". | com.shaft.tools.io.ReportManager - main - 05:28:29 PM 
[INFO] Attempting to run remotely on: "ANDROID | http://127.0.0.1:4723/". | com.shaft.tools.io.ReportManager - main - 05:28:29 PM 
[INFO] Capabilities {appium:allowTestPackages: true, appium:app: /Users/robert.saveanu/Downl..., appium:appWaitActivity: *, appium:autoAcceptAlerts: true, appium:autoGrantPermissions: true, appium:automationName: uiautomator2, appium:clearDeviceLogsOnStart: true, appium:disableWindowAnimation: true, appium:enableWebviewDetailsCollection: true, appium:enforceAppInstall: false, appium:forceAppLaunch: true, appium:fullReset: false, appium:ignoreHiddenApiPolicyError: true, appium:isHeadless: true, appium:noReset: true, appium:noSign: true, appium:platformVersion: 14.0, appium:printPageSourceOnFindFailure: true, appium:shouldTerminateApp: true, appium:showChromedriverLog: true, language: en, locale: US, unlockKey: 1988, unlockType: pin} | com.shaft.tools.io.ReportManager - main - 05:28:29 PM 
[INFO] Attempting to instantiate remote driver instance for up to 10min. | com.shaft.tools.io.ReportManager - main - 05:28:29 PM 
[INFO] Loaded OpenCV "opencv_java490". | com.shaft.tools.io.ReportManager -  - 05:28:30 PM 
[INFO] Engine Update check done for the day. 👍 | com.shaft.tools.io.ReportManager -  - 05:28:32 PM `

**Environment**

 1. SHAFT_Engine version: **8.2.20240611**
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable): **8.2.20240523**
 
**To Reproduce**

 Try running any test

**Comment by MohabMohie** [comment]
Initial investigation shows that changes from Appium side are breaking some desired capabilities in favor of os specific options classes.

Further investigation is needed, upgrading the implementation to use options is recommended.
