### ISSUE TITLE
[Bug]: Allure Report is not allowed to be opened with size less than 400 mb

### ISSUE THREAD

**Issue by mostafamohab** [ShaftHQ/SHAFT_ENGINE#1665]
Problem:
Allure Report not opening after being downloaded with file less than 400mb and Shaft Version 8.2.20240411

**Screenshots**
<img width="377" alt="Allure Shaft Version" src="https://github.com/user-attachments/assets/4528bcea-ff9b-4e79-a181-1178874ba745">

<img width="598" alt="Allure Downloaded File" src="https://github.com/user-attachments/assets/2f810222-ccb7-4da1-b791-cb1a7e5b1a90">

<img width="956" alt="Allure Not Opening" src="https://github.com/user-attachments/assets/f4a384fc-db33-4cd4-bee7-54694a2e685e">

**Comment by MohabMohie** [comment]
@mostafamohab I think this is related to allure dear not to SHAFT.

From our side, all our allure reports in our GitHub actions pipeline are less than 400mb in size and all of them are working fine after download.
