### ISSUE TITLE
[Feature Request]: add configuration to allow the override of the current allure report html file

### ISSUE THREAD

**Issue by themosaeed** [ShaftHQ/SHAFT_ENGINE#1672]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

configuration to allow the override of the current allure report html file

**Comment by zanoon2020** [comment]
Dear @themosaeed , kindly explain more what you mean by override current html , do you mean keep history and each time html report contains current and past run ?

**Comment by themosaeed** [comment]
@zanoon2020  right now the behavior is that with each run a new HTML report is generated and added to the folder alongside the old one. What we need is the option to do this or delete the old one and keep only the most recent report.

**Comment by zanoon2020** [comment]
Dear @themosaeed if you are using custome property file try the below property and feedback : 

 cleanAllureResultsDirectoryBeforeExecution=true 

But take into consideration that will **wipe** the allure history and just keep the last run.

**Comment by themosaeed** [comment]
@zanoon2020  this clears the allure-results folder but doesn't delete the old HTML report generated in allure-report folder. still adds new one and keeps the old HTML file

**Comment by zanoon2020** [comment]
Thanks @themosaeed for feedback , 

We will discuss it and get back to you

**Comment by MohabMohie** [comment]
@zanoon2020 what I understand is that we need to modify the behavior of "cleanAllureResultsDirectoryBeforeExecution" to clean both the allure results and allure reports directories.
which makes sense...
shall I leave that to you? I remember you wanted to pickup a small task to warm up.

**Comment by zanoon2020** [comment]
@MohabMohie i think the question is , we want to clean allure results directory and leave allure report history. And in this situation allure report folder will have it's own flag. Do you agree on this

**Comment by MohabMohie** [comment]
related to #1566
I will restructure the current allure properties and move them to a dedicated "Allure" properties object for better management. this will be a breaking change but will allow the user more customization.
