### ISSUE TITLE
[Bug]: Execution Summary report is not showing the number of passed/failed validations

### ISSUE THREAD

**Issue by MohamedHazem95** [ShaftHQ/SHAFT_ENGINE#1680]
After upgrading to JDK 21 and Shaft version 8.x , Execution summary report is not showing the validations numbers , it's always showing Zeroes for the total/passed/failed validations.

**Environment**

 1. Current Shaft version 8.2.20240624
 2. Last SHAFT_Engine version that did not exhibit the issue : 7.4.20231026
 3. Desktop OS: Windows 11
 4. Desktop Browser : Chrome
 5. Desktop Browser Version : 127.0.6533.73

**To Reproduce**

1- Run any test case with multiple steps.
2-After execution is done , Open the execution summary report.
3-Inspect the validations section in the report

**Expected behavior**

Total Validations number / Passed Validations / Failed Validations should be shown correctly.

**Screenshots**

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/9f40e711-dc03-4984-8e89-2b7411083781">

[Reports.zip](https://github.com/user-attachments/files/16486953/Reports.zip)

**Comment by MahmoudElSharkawy** [comment]
Thanks for reporting; Will investigate and let you know ASAP isA.
