### ISSUE TITLE
[Bug]:  unexpected error when use this function driver.element().assertThat(locator).matchesReferenceImage(),

### ISSUE THREAD

**Issue by NohairWaffarX** [ShaftHQ/SHAFT_ENGINE#1696]
when use this function driver.element().assertThat(locator).matchesReferenceImage(), there is unexpected error appear which appear in attachment 

![Screenshot_2](https://github.com/user-attachments/assets/309d0fd1-68cc-453f-a363-1a1282dc81ef)

**Comment by MohabMohie** [comment]
closing issue due to missing information. kindly feel free to reopen when you want to provide the needed info.
