### ISSUE TITLE
[Bug]: when used function clear, it clear data and then , error appear that can't find element to clear it

### ISSUE THREAD

**Issue by NohairWaffarX** [ShaftHQ/SHAFT_ENGINE#1702]
**Describe the bug**

When used function clear, it clear data and then , error appear that can't find element to clear it

**Link to SHAFT_Engine Console logs**
![image](https://github.com/user-attachments/assets/e3469e84-ed95-4672-9d8f-273813b8de45)

**Environment**
SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):
Last SHAFT_Engine version that did not exhibit the issue (if applicable):
Mobile Device Name (Redmi)
Mobile Device OS (Android)
Mobile Device Native App (WaffarX)

**To Reproduce**

1-open app
2-Login with account [gnohair@gmail.com](mailto:gnohair@gmail.com) & password:: Ng555555
3-click on menu
4-Click on cashback on gift card
5-Click on purchase gift card
6-click on amazon Egypt (we found default value 10)

**Expected behavior**
Value 10 clear and test case passed

**Screenshots**
![image](https://github.com/user-attachments/assets/c2f94261-dfea-44c7-a800-cdb6bc19106f)

**Comment by MustafaAgamy** [comment]
Can you please provide a link for the app to download, in order to be able to investigate further?

Thank you.

**Comment by NohairWaffarX** [comment]
App called Waffarx , you can download it from app store

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MohabMohie** [comment]
kindly use this flag 'forceCheckTextWasTypedCorrectly=false' after the new version is released
