### ISSUE TITLE
[Bug]: Unable to run tests locally(MAC) after upgrading from v 8.2.20240411 to 8.2.20240523 or latest version

### ISSUE THREAD

**Issue by myoussef87** [ShaftHQ/SHAFT_ENGINE#1710]
**Describe the bug**

Unable to run tests on MAC locally on the latest version of SHAFT

**Exception logs**

https://gist.github.com/myoussef87/aa49c0c8e72d1821441a5375dd343cd0
https://gist.github.com/myoussef87/f32628798495a5d56ea2b5527d2c1fa1

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 8.3.20240813 and 8.2.20240523 (Start from this release)
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):8.2.20240411
 3. Desktop OS: Mac
 4. Desktop Browser (if applicable): Any Browser (Chrome in this case)
 5. Desktop Browser Version (if applicable): Version 127.0.6533.120
 6. Mobile Device Name (if applicable): N/A
 7. Mobile Device OS (if applicable): N/A
 8. Mobile Device Browser or Native App: N/A 
 9. Mobile Device Browser (if applicable): N/A
 10. Mobile Device Browser Version (if applicable): N/A

**To Reproduce**

1. Set "targetBrowserName" as "chrome"
2. Run any test method

**Expected behavior**

Browser launched and test execution begin instead browser open then closed multiple times without starting test execution.

**Screenshots**
https://app.screencast.com/Q0FVWpLGHuSBU

**Additional context**

**Comment by MohabMohie** [comment]
Related to

https://www.selenium.dev/blog/2024/chrome-browser-woes/

I'm sitting to

**Comment by MohabMohie** [comment]
Close by mistake

**Comment by MohabMohie** [comment]
Issue is not reproducible on all Mac devices. But is still valid.

**Comment by myoussef87** [comment]
If this help, here is my MAC info
![image](https://github.com/user-attachments/assets/9071edbf-7872-4c22-9020-805df814ae01)

**Comment by myoussef87** [comment]
If you need any other details , please tell me.
Thanks in advance

**Comment by myoussef87** [comment]
Added the latest exception to the description and updated the title
