### ISSUE TITLE
[Bug]: Unable to launch Chrome/MS Edge browser on MAC - Shaft ver : 8.3.20240924-beta

### ISSUE THREAD

**Issue by myoussef87** [ShaftHQ/SHAFT_ENGINE#1751]
**Describe the bug**

When trying to run any test classes against MAC/Chrome it is stuck and Chrome browser is not launched.

**Link to SHAFT_Engine Console logs**
https://gist.github.com/myoussef87/351adecff198d36784bd58246c9d36ce

**Link to Allure Report HTML**

https://gist.github.com/myoussef87/ef17ca28df98252a4f920f7fbb5cfd2a

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 8.3.20240924-beta
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable): N/A
 3. Desktop OS: MAC Pro/Sonoma 14.7 (23H124)
 4. Desktop Browser (if applicable): Chrome / MS Edge
 5. Desktop Browser Version (if applicable): Version 129.0.6668.60 (Official Build) (arm64)
 6. Mobile Device Name (if applicable): N/A
 7. Mobile Device OS (if applicable): N/A
 8. Mobile Device Browser or Native App:  N/A
 9. Mobile Device Browser (if applicable): N/A
 10. Mobile Device Browser Version (if applicable): N/A

**To Reproduce**

1. Follow the steps to run SHAFT https://github.com/ShaftHQ/testng-archetype for the first time with latest version

**Expected behavior**

Browser launched and tests started to be executed

**Screenshots**

https://app.screencast.com/Ih0FJZROCObvM

**Additional context**

**Comment by MohabMohie** [comment]
maybe related to https://github.com/SeleniumHQ/selenium/issues/13676 ??

**Comment by MohabMohie** [comment]
Please note that I was not able to reproduce the issue on BrowserStack and the browser opened successfully using the same configuration you provided:

```properties
executionAddress=browserstack
targetOperatingSystem=MAC
browserStack.os=OS X
browserStack.osVersion=Sonoma
targetBrowserName=Chrome
browserStack.browserVersion=latest
```

However, I noticed that you're using Chrome 129, whereas the latest supported on BrowserStack is 128. Can you try to downgrade and retest?

**Comment by myoussef87** [comment]
I don't think that https://github.com/SeleniumHQ/selenium/issues/13676 is related, as my issue is for local running on MAC and the issue in the link is related to running on grid with Linux setup.
It was working fine for me 3 weeks ago, but now it is not working, maybe the issue is only reproduced on my machine only.
I'm not able to debug on my machine.

The same setup is working fine if I run it against remote server (Linux Machine.)

Also the same issue happens in Firefox so I don't think it is related to browser , maybe there is some thing preventing access to perform actions on my MAC , do you have any idea to debug this?

**Comment by MohabMohie** [comment]
I only know the steps to enable Safari, would you kindly try those and see if you can get safari to work?

https://developer.apple.com/documentation/safari-developer-tools/macos-enabling-webdriver

**Comment by myoussef87** [comment]
Thanks @MohabMohie for your support.
