### ISSUE TITLE
[Bug]: can't use the correct platform value when run on selenium grid

### ISSUE THREAD

**Issue by sarahelghayaty** [ShaftHQ/SHAFT_ENGINE#1785]
I'm using shaft version 8.3.20240829 and every time I tried to run on selenium grid , the platform set to LINUX regardless the platform value I set in prop file. is this a way to use my own value not the default one

**Comment by MohabMohie** [comment]
dear @sarahelghayaty , we are unable to reproduce this issue from our side. kindly reopen the issue with all the required information from the issue template so that we can debug it further.
