### ISSUE TITLE
[Bug]: Logj4j logs url credentials in "navigatToUrl" method

### ISSUE THREAD

**Issue by roaamagdy** [ShaftHQ/SHAFT_ENGINE#1801]
Some urls has the following format  https://username:password@host/... so when using `navigatToUrl` method, it logs the full url with the authentication data and for security reason this should be avoided.

Current solution it to change the log4j level to anything rather than info.

I tried to add regex expression, filters or custom PatternLayout to log4j file but it wasn't read .

**Comment by MohabMohie** [comment]
simple test
<img width="876" alt="image" src="https://github.com/user-attachments/assets/1f4234ae-f02f-443b-86ba-6bcaf11bb822">

result before
<img width="632" alt="image" src="https://github.com/user-attachments/assets/b262043a-d2c6-419f-bc96-9ee558d6001e">


result after
<img width="865" alt="image" src="https://github.com/user-attachments/assets/4079665d-b9fb-4024-a5e9-d642d20b566d">

**Comment by roaamagdy** [comment]
@MohabMohie same happen in :

- Get current url
- Initial URL
