### ISSUE TITLE
Can not run cucumber features in parallel

### ISSUE THREAD

**Issue by yahiaelaydy** [ShaftHQ/SHAFT_ENGINE#631]
**Description**
I'm trying to run cucumber features in parallel but it does not work and I'm using this annotation
![image](https://user-images.githubusercontent.com/100137344/173814781-a8c1a689-7346-4e0e-83ec-9577bc4f83bd.png)
![image](https://user-images.githubusercontent.com/100137344/173814883-2748a597-5adf-4ff3-8252-88fa3b132a31.png)

Also I have checked Test Automation Hero++ playlist and updated my code accordingly and it keeps running in sequence not in parallel.

**Comment by MohabMohie** [comment]
Please note that upon investigation no issues were found. But there is a missing piece of configuration and it should be included in the user guide ( @themosaeed  to align with sondos )

To execute cucumber features in parallel you need the following:
1. To use ThreadLocal webdrivers, or the new SHAFT Wizard Syntax. (DONE)
2. To configure your test runner for parallel execution via dataprovider. (DONE)
3. To configure your TestNG properties to allow for parallel execution. (MISSING)
![image](https://user-images.githubusercontent.com/19201898/175717745-de7e87f9-40f9-46e7-bb5e-0628a8d8e08a.png)
Note that I chose to set parallel to "METHODS", and to raise the number of threads to "3" overall, and "3" to the dataprovider.

Running with the above configuration produced the desired results. Note that all the tests started at 0:00 whereas the sequential tests do not do the same.

Parallel tests timeline:
![image](https://user-images.githubusercontent.com/19201898/175719102-a2081e95-8b0d-4369-8647-194cb1bcfec5.png)

Sequential tests timeline:
![image](https://user-images.githubusercontent.com/19201898/175719130-c7f8d3df-e41e-4174-bb2a-935050a93b63.png)
