### ISSUE TITLE
When used SwipeElementIntoView(Element, TouchActions.SwipeDirection.DOWN), get "element locator is NULL" Error

### ISSUE THREAD

**Issue by Mohab-Osama** [ShaftHQ/SHAFT_ENGINE#641]
When used SwipeElementIntoView(Element, TouchActions.SwipeDirection.DOWN), get "element locator is NULL" Error

**To Reproduce**
1. Add SwipeElementIntoView(Element, TouchActions.SwipeDirection.DOWN) 
ex: ElementActions.performTouchAction(driver).swipeElementIntoView(M2, TouchActions.SwipeDirection.DOWN);

2. Run test

**Expected behavior**
Element swipe into view successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/108004467/175036687-13ced2de-e218-470f-8f0f-6c541587eacb.png)

Issue occurred while testing native android app and could simulate it in chrome desktop browser SHAFT_ENGINE version 6.2.20220609.

**Desktop :
 - OS: Windows
 - Browser Chrome
 - Version 102

**Smartphone :
 - Device: [e.g. Galacy J5]
 - OS: [e.g. Android 9]

**Comment by MohabMohie** [comment]
done and will be pushed with the next release.
