### ISSUE TITLE
new validation for equalsFileIgnoringOrder

### ISSUE THREAD

**Issue by Ghadeermoh** [ShaftHQ/SHAFT_ENGINE#644]
**Is your feature request related to a problem? Please describe.**
When I try to validate a response with Json file and the response is nested I can't do correct validation 
**Describe the solution you'd like**
need new feature to be able to validate file ignoring order as contentfile always fail with me 
**Describe alternatives you've considered**

**Additional context**

**Comment by MohabMohie** [comment]
implemented and will be pushed with the coming release.

sample code:
![image](https://user-images.githubusercontent.com/19201898/175698916-cebae23e-da5f-4ec5-bf92-2c60bfbff2e5.png)

sample report:
![image](https://user-images.githubusercontent.com/19201898/175698959-a3a523b8-7d21-479a-a902-0a0b0b435b5a.png)
![image](https://user-images.githubusercontent.com/19201898/175699006-9f841f46-5755-40e8-8140-3fad090c4183.png)
