### ISSUE TITLE
IOS/Mac - Unexpected selection of asserted element in the report

### ISSUE THREAD

**Issue by norasalah2828** [ShaftHQ/SHAFT_ENGINE#675]
**Description**
When you assert on specific element then you check the report you will find the green highlight rectangle is selecting a different empty space in the screen instead of the exact element.

**To Reproduce**
Assert on any element using " Validations.verifyThat()
                .element(driver, new Tutorial(driver)
                        .getTutorial_text())
                        .exists()
                       .perform();"

**Expected behavior**
The element which you are asserting on should be selected in the screenshot, for the mention example in the screenshot it should select "Your Account in your hands" text 

**Screenshots**
https://prnt.sc/9aQ7SMaz3qL6

**Smartphone**
 - Device: [Iphone 12 pro max]
 - OS: [iOS 15.6]

**Additional context**
- The issue is happening on shaft version "6.3.20220808".
- It tested on many elements.

**Comment by MohabMohie** [comment]
kindly upgrade to the latest beta, make sure you are using only one screen (no external screen connected to the laptop, and reopen with a fresh allureArchive attached if the issue still exists.
