### ISSUE TITLE
After update to latest version (6.3.20220808) an error appears in some restassured old testcases

### ISSUE THREAD

**Issue by Mohab-Osama** [ShaftHQ/SHAFT_ENGINE#680]
After update to latest version (6.3.20220808) this error appears in some restassured old testcases that was working fine:

**Error:**
	java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.datatype.jdk8.Jdk8Module not found

Code:

    @Step("set add CC Second Patch request body")
    public JSONObject addCCSecondPatchSetBody( String documentId) {
        JSONObject SecondPatch_Payload = new JSONObject();

        SecondPatch_Payload.put("cardMask", "454881******7774");
        SecondPatch_Payload.put("documentID", documentId);
        SecondPatch_Payload.put("documentType", "Passport");
        SecondPatch_Payload.put("expiryDate", "2404");
        SecondPatch_Payload.put("journey", "106");
        SecondPatch_Payload.put("token", "1000000000000023");
        return SecondPatch_Payload;
    }

    @Step("pay for add CC Second Patch")
    public Response payForCCSmartPaySecondPatch(String documentId) {
        String payForCCEndPointSecondPatch = "es/v1/customerAccounts/"+documentId+"/payments";
        JSONFileManager users = new JSONFileManager(System.getProperty("testDataFolderPath") + "testUsers.json");
        Response payForCCSmartPayFirstPatchResponse = this.restActions.buildNewRequest(payForCCEndPointSecondPatch, 
		RequestType.PATCH).setRequestBody(this.addCCSecondPatchSetBody("P505184"))
                .addHeader("vf-target-environment","aws-pprd-es")
                .setContentType("application/merge-patch+json")
                .addHeader("Accept","application/json")
                .appendDefaultContentCharsetToContentTypeIfUndefined(false)
                .setTargetStatusCode(200).performRequest();
        return payForCCSmartPayFirstPatchResponse;
    }

    @Test
    public void ensurepayForCCSmartPaySecondPatchWorks() {
        Response PayForAddCCResponse = this.smartPayAPIs.payForCCSmartPaySecondPatch("P505184"));
        String Response = RestActions.getResponseJSONValue(PayForAddCCResponse, "collection");
        System.out.println(Response);
        Validations.verifyThat().object(Response).contains("wallet_credit_card").perform();
    }
	
**Screen shot for the error:**
<img width="873" alt="Err1" src="https://user-images.githubusercontent.com/108004467/185115093-3ab38817-03bc-47a1-899d-5a91644efeaf.PNG">

<img width="872" alt="Err2" src="https://user-images.githubusercontent.com/108004467/185115118-236a0a4d-f5b7-4a12-85d7-618a500348f7.PNG">

**Comment by MohabMohie** [comment]
please include screenshots from the full exception stacktrace, pasting the stacktrace is not helpful.
@MahmoudElSharkawy would you like to take a look?

**Comment by MahmoudElSharkawy** [comment]
I'm waiting the full exception stacktrace.
Also, cam you please provide a reproducible class with an example to be able to investigate?

**Comment by Mohab-Osama** [comment]
@MohabMohie New screen shots uploaded for the error, @MahmoudElSharkawy  I can't find simple class that reproduce this error.

**Comment by MohabMohie** [comment]
@Mohab-Osama  which engine version was working fine?

**Comment by Mohab-Osama** [comment]
@MohabMohie  6.2.20220408

**Comment by MohabMohie** [comment]
kindly upgrade to the latest beta and reopen with a fresh stacktrace if the issue still exists.
