### ISSUE TITLE
Exceptions when clicking on element 

### ISSUE THREAD

**Issue by MhmdElGazzar** [ShaftHQ/SHAFT_ENGINE#681]
**Describe the bug**
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] org.openqa.selenium.interactions.MoveTargetOutOfBoundsException:
move target out of bounds
  (Session info: chrome=104.0.5112.81)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'E0727734', ip: '192.168.1.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0ae53d5d16e4622abe9bf616caf9ef23, actions {actions=[org.openqa.selenium.interactions.Sequence@3b577709]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 104.0.5112.81, chrome: {chromedriverVersion: 104.0.5112.79 (3cf3e8c8a07d..., userDataDir: C:\Users\AMRELG~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:9222}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:9222/devtool..., se:cdpVersion: 104.0.5112.81, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 30000, script: 30000}, unhandledPromptBehavior: accept and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0ae53d5d16e4622abe9bf616caf9ef23
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:626)
org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:656)
org.openqa.selenium.interactions.Actions.perform(Actions.java:612)
com.shaft.gui.element.WebDriverElementActions.click(WebDriverElementActions.java:120)
com.shaft.gui.element.ElementActions.click(ElementActions.java:71)
PageObjectModel.FE.Dashboard.navigateToGroupFromGridView(Dashboard.java:256)
StepDefinition.FE.Dashboard_StepDef.navigateToGroupFromTheGridViewInTheDashboard(Dashboard_StepDef.java:110)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
io.cucumber.java.Invoker.invoke(Invoker.java:24)
io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
io.cucumber.core.runner.TestStep.run(TestStep.java:57)
io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
io.cucumber.core.runner.TestCase.run(TestCase.java:95)
io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:151)
io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:151)
io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
org.testng.TestRunner.privateRun(TestRunner.java:808)
org.testng.TestRunner.run(TestRunner.java:603)
org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
org.testng.SuiteRunner.run(SuiteRunner.java:326)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
org.testng.TestNG.runSuites(TestNG.java:1092)
org.testng.TestNG.run(TestNG.java:1060)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) @16-08-2022 16:31:10.0110 PM

**To Reproduce**
1. using this code
ElementActions.click(TestBase.getDriver(), By.id("UM_GrpTable_Row_ArrowCollapsed_" + groupName));
2.the element needs scrolling to be visible 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser chrome

**Comment by MohabMohie** [comment]
I'm unable to trace this stacktrace, it's not aligned with the latest engine version. Kindy upgrade and send a complete allure report archive to be able to debug.

Attempt to implement a blind fix has failed.

PS: It always helps if you attach a code block that can help reproduce the issue if applicable.

**Comment by MhmdElGazzar** [comment]
it didn't successed to retirieve the latest version of shaft 
jforg didn't recognize it , so i continued with the last working version with us

**Comment by MohabMohie** [comment]
Please note that the latest version is working fine. It's probably an issue with your local maven repo.
Kindly upgrade and send a complete allire report archive to be able to debug.

**Comment by MohabMohie** [comment]
kindly upgrade to the latest beta and reopen with a fresh stacktrace if the issue still exists.
