### ISSUE TITLE
Mobile issue - While scrolling down inside scroll view , Shaft clicks on random element inside that view

### ISSUE THREAD

**Issue by hossameldinmohamed** [ShaftHQ/SHAFT_ENGINE#714]
**Describe the bug**
When i try to scroll down inside scroll view in android application , out of 10 times  9 trials succeeded and the tenth trial fails as shaft clicks on random element before the scrolling  

**To Reproduce**
1. Run scrolling test on android app
2. Try to scroll till the end of the screen
3. Repeat the test many times then notice the behavior

**Expected behavior**
The scrolling should work fine every single time 

**Smartphone (please complete the following information):**
 - Device:  Samsung Galaxy A52 5g
 - OS: Android
 - Version :12
 
**Command Used for scrolling**
new TouchActions(driver).swipeElementIntoView(ElementLocator, TouchActions.SwipeDirection.DOWN);

**Additional context**
For all scrolling cases (Success - Fail ) the below log found while try to scroll to the specified element 
https://codeshare.io/8p6Knv

There is no special logs for the failed cases as shaft click on random element then try to scroll but the app already navigated to another screen due to that click  so it failed because it didn't find the required text to scroll

**Comment by MohabMohie** [comment]
Hello @hossameldinmohamed , I'm having a hard time reproducing / debugging this case with my existing test code... can you share some real code with me to help me debug?

**Comment by hossameldinmohamed** [comment]
@MohabMohie i'm sorry for the late reply. i know the debugging in that case won't be easy at all. I tried the same scenario multiple times for around 2 hours and didn't try it again ever since. I will try it again with other apps as last time i was doing some trials for internal app in our company.
We can close the issue for now and once i have any update i will share it

**Comment by MohabMohie** [comment]
@hossameldinmohamed thank you. I'll await your updated input.
