### ISSUE TITLE
SHAFT skip executing all next tests if the before method fails

### ISSUE THREAD

**Issue by Kinasr** [ShaftHQ/SHAFT_ENGINE#715]
**Describe the bug**
When running a class of tests and on one on those test the BeforeMethod fails, all next tests in this class are skipped

**To Reproduce**
1. Create new SHAFT project
2. Create a test class
3. Define the @BeforMethod class and make it fails
4. Define some test methods

``` java
@BeforeMethod
    void setUp() {
        fail();
    }

    @Test
    void ttt1() {
        System.out.println("01");
    }

    @Test
    void ttt2() {
        System.out.println("02");
    }

    @Test
    void ttt3() {
        System.out.println("03");
    }
```

**Expected behavior**
Even if the Before Method fail one time this doesn't mean that it will fail in all times to skip the all coming test.
The Failure of Before Method shouldn't case other tests to be skipped.

**Screenshots**
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/52010908/191283230-050abfdb-52da-4b76-ab20-b13aa4875ac3.png">

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 105.0.5195.127

**Comment by MohabMohie** [comment]
Please note that this is not a bug. This is the default behavior for TestNG. In the code you shared, you're not using SHAFT at all.
