### ISSUE TITLE
Swiping horizontally using Appium not responding

### ISSUE THREAD

**Issue by ahmed-madyan** [ShaftHQ/SHAFT_ENGINE#742]
Swiping gestures not responding when I try to swipe horizontally, as per Appium documentation we need to differentiate between scroll and swipe gestures, I suggest implementing a separate method for each action instead of using the same method.

**Comment by MohabMohie** [comment]
Will close due to lack of activity until @ahmed-madyan shares more info here as requested privately

**Comment by ahmed-madyan** [comment]
@MohabMohie I am already started working on using an offline branch and will push it when it is ready.

**Comment by MohabMohie** [comment]
@ahmed-madyan as discussed the existing implementation matches what's on the documentation, and it's already working as expected on the test app.

We need more info, what exactly isn't working? What got it to work? Then we can study the fix.
