### ISSUE TITLE
[Feature] Start and stop Appium server automaticlly

### ISSUE THREAD

**Issue by sultanpaymob** [ShaftHQ/SHAFT_ENGINE#744]
We need to add in MobileCapabilities.properties the ability to start and stop the Appium server programmer to move forward to be a standalone framework and just depend on the emulator app only as an external support app

**Comment by MohabMohie** [comment]
That's perfectly doable... Would you like to own the implementation?

**Comment by sultanpaymob** [comment]
Let's try to to do it

Thanks

Muhammad L. Sultan
CTAL-TM®, PMP®, SFPC®
Head Of Software Quality
Mobile: +20 1004822119
Email: ***@***.***
Address: Building 7H, Street 263 New Maadi, Cairo, Egypt
Website: www.paymob.com
________________________________

**Comment by MohabMohie** [comment]
Ps. I encourage you to open a PR and add paymob to the list of SHAFT users

**Comment by sultanpaymob** [comment]
For sure, it's a pleasure to that

Thanks

Muhammad L. Sultan
CTAL-TM®, PMP®, SFPC®
Head Of Software Quality
Mobile: +20 1004822119
Email: ***@***.***
Address: Building 7H, Street 263 New Maadi, Cairo, Egypt
Website: www.paymob.com
________________________________
