### ISSUE TITLE
[Docs] User need more clarification for how to configure Docker Desktop to use Linux images. 

### ISSUE THREAD

**Issue by sultanpaymob** [ShaftHQ/SHAFT_ENGINE#745]
it's perfect to use Docker for Sequential or Parallelized execution but we should guide the user on how to configure Docker Desktop to use Linux images. however, this guidance is in a list of steps or videos.

**Comment by MohabMohie** [comment]
you mean we should refer to this link: https://docs.docker.com/desktop/install/windows-install/ on our user guide? or on the configuration manager? or do you mean something else?

**Comment by sultanpaymob** [comment]
Hello Mohab,

Firstly, I would like to thank you.

  1.  We can add the below URL for Docker Download

https://docs.docker.com/desktop/

  1.  If we need to add any configurations after downloading, we should to clear it.

Currently we face an issue once try to use Dockerized Execution with Sequential or Parallelized


Thanks,

 [signature_1587260761] -
Muhammad L. Sultan
CTAL-TM®, PMP®, SFPC®
Head Of Software Quality
Mobile: +20 1004822119
Email: ***@***.******@***.***>
Address:  Building 7H, Street 263 New Maadi, Cairo, Egypt
Website: www.paymob.com<https://eur06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.paymob.com%2F&data=05%7C01%7Cmuhammad.sultan%40paymob.com%7Ca2c760e11a9543bedba508da5ff616bd%7C96bf202797ea4dfc8f5b7121b770f292%7C0%7C0%7C637927807791050092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DZEt0WkcBEONWRd0B0yH3YcWQmJIK4abaL0d6BmbqFc%3D&reserved=0>

At Paymob, we don’t settle for “Good enough” or “Great Enough”, we work to be the Best, the Greatest, or to be second to no one.

From: Mohab Mohie ***@***.***>
Date: Monday, October 24, 2022 at 9:32 AM
To: ShaftHQ/SHAFT_ENGINE ***@***.***>
Cc: Muhammad Sultan ***@***.***>, Author ***@***.***>
Subject: Re: [ShaftHQ/SHAFT_ENGINE] User need more clarification for how to configure Docker Desktop to use Linux images. (Issue #745)

you mean we should refer to this link: https://docs.docker.com/desktophttps://docs.docker.com/desktop/#:~:text=Install%20Docker-,Desktop,-Install%20on%20Mac/install/windows-install/<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.docker.com%2Fdesktop%2Finstall%2Fwindows-install%2F&data=05%7C01%7Cmuhammad.sultan%40paymob.com%7Ccaf83ac63efa4374a81e08dab591e037%7C96bf202797ea4dfc8f5b7121b770f292%7C0%7C0%7C638021935378601000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FJyOR3%2BmaWd4msqXufH0lvO%2FhFBeTkpbXZrvKIHbzxM%3D&reserved=0> on our user guide? or on the configuration manager? or do you mean something else?

—
Reply to this email directly, view it on GitHub<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FShaftHQ%2FSHAFT_ENGINE%2Fissues%2F745%23issuecomment-1288545295&data=05%7C01%7Cmuhammad.sultan%40paymob.com%7Ccaf83ac63efa4374a81e08dab591e037%7C96bf202797ea4dfc8f5b7121b770f292%7C0%7C0%7C638021935378601000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U83FtEyRw4g1w3dG74%2BN7WoXUgFkNn6yGj8limdnQc0%3D&reserved=0>, or unsubscribe<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2B3ZUD633SJW3OZCND5V53WEY3P7ANCNFSM6AAAAAARMV32EU&data=05%7C01%7Cmuhammad.sultan%40paymob.com%7Ccaf83ac63efa4374a81e08dab591e037%7C96bf202797ea4dfc8f5b7121b770f292%7C0%7C0%7C638021935378757211%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NVBqQEU4DOtpmD2Z3IpBTI24SIF5SyLAXujWY4dwO%2F4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

The contents of this e-mail message and any attachments are confidential and are intended solely for the addressee. It is strictly forbidden to share any part of the information included in this email or its attachments with any third party, without a written consent of the sender. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.
