### ISSUE TITLE
[Bug] The window is not maximized automatically with FireFox browser

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [ShaftHQ/SHAFT_ENGINE#749]
- Browser: FireFox
The window is not maximized automatically with FireFox browser when the autoMaximizeBrowserWindow property is enabled.

**Comment by MohabMohie** [comment]
Please share:
Firefox version
Screen setup (single or multi monitor)
OS name and version 
Headless or normal

**Comment by MahmoudElSharkawy** [comment]
Firefox version: 106.0.1
Screen setup: single
OS name: windows
Headless or normal: normal
