### ISSUE TITLE
The setup step fails after any change in the properties file || Reopen Bug

### ISSUE THREAD

**Issue by sultanpaymob** [ShaftHQ/SHAFT_ENGINE#754]
The setup step fails after any change in the properties file 
https://github.com/ShaftHQ/SHAFT_ENGINE/issues/740#issue-1412282784

**Comment by MohabMohie** [comment]
can you share an updated stacktrace please and confirm using the latest engine version?
it's not the same issue in-code, but it can be something else that has a very similar impact.

**Comment by sultanpaymob** [comment]
it's just crash
