### ISSUE TITLE
[Feature] Implement some out of the box waits in SHAFT to handle certain cases

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [ShaftHQ/SHAFT_ENGINE#756]
Implement some out of the box waits in SHAFT to handle certain cases like waiting an element to be invisible and other cases that can't be handled by SHAFT built-in waits with the actions automatically.

**Comment by MahmoudElSharkawy** [comment]
I think this is covered with the waitForElementToBePresent method enhancements, right?
I don't think of any waits needed now. Let's close this and We can reopen it when needed.
What do you think @MohabMohie ?

**Comment by MohabMohie** [comment]
Agreed
