### ISSUE TITLE
SHAFT Logs "Starting Dynamic Cucumber Feature Execution" and desn't go through setup or tear down activities when executing TestNG groups

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [ShaftHQ/SHAFT_ENGINE#771]
![image](https://user-images.githubusercontent.com/46620378/201334230-0e7ccf27-71e1-4032-bf1c-dbb0f4ffda36.png)

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy will you self assign this, or should I take it?
