### ISSUE TITLE
Report doesn't open automatically on some corporate machines

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#781]
The report doesn't open automatically, and the generate_allure_report.bat file opens and closes without doing anything.

**Comment by MohabMohie** [comment]
Workaround was identified to edit the batch file manually and override the JAVA_HOME variable with the one that SHAFT generates.

old:
![image](https://user-images.githubusercontent.com/19201898/204762289-f883f552-4b11-4f79-8bc2-c8b5d962f141.png)

new:
![image](https://user-images.githubusercontent.com/19201898/204762233-84feb40c-05bf-4ea6-869f-c20139fe0078.png)

**Comment by MohabMohie** [comment]
Hi @mahmoudYosrey the fix was released a few minutes ago. Please just update to the latest engine version and get back to me to confirm if it's working for you now.

**Comment by mahmoudYosrey** [comment]
Hi @MohabMohie the problem still exist with me
