### ISSUE TITLE
Fatal error compiling- invalid target release: 17

### ISSUE THREAD

**Issue by LakshmananKuppan** [ShaftHQ/SHAFT_ENGINE#785]
I am trying to use the Shaft Engine but I am facing a compilation issue.

Steps I followed:
1. Created ed Java Meven project.
2. Opened the pom.xml and copy pasted the ShaftEngine pom.xml highlighted content.
3. Saved and all the maven dependencies and plugins were downloaded.
4. Created a sample package and a class.
5. Wrote single sample print statement.
6. Tried to run by right clicking of the class and selected Run as Maven clean and Maven test.

I got the following issues:
[INFO------------< [0;36mweb_Automation:webAutomationWithShaftEngine[0;1m >-------------[m
[INFOBuilding webAutomationWithShaftEngine 0.0.1-SNAPSHOT[m
[INFO--------------------------------[ jar ]---------------------------------[m
[ INFO--- [0;32mmaven-resources-plugin:2.6:resources[m [1m(default-resources)[m @ [36mwebAutomationWithShaftEngine[0;1m ---
[WARNINGUsing platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO skip non existing resourceDirectory /Users/lakshmanan/eclipse-workspace/webAutomationWithShaftEngine/src/main/resources
[INFO
[INFO --- [0;32mmaven-compiler-plugin:3.10.1:compile[m [1m(default-compile)[m @ [36mwebAutomationWithShaftEngine[0;1m ---
[INFONothing to compile - all classes are up to date
[INFO
[INFO--- [0;32mmaven-resources-plugin:2.6:testResources[m [1m(default-testResources)[m @ [36mwebAutomationWithShaftEngine[0;1m ---
[WARNINGUsing platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFOskip non existing resourceDirectory /Users/lakshmanan/eclipse-workspace/webAutomationWithShaftEngine/src/test/resources
[ INFO--- [0;32mmaven-compiler-plugin:3.10.1:testCompile[m [1m(default-testCompile)[m @ [36mwebAutomationWithShaftEngine[0; ---
[ INFOChanges detected - recompiling the module!
[INFO Compiling 1 source file to /Users/lakshmanan/eclipse-workspace/webAutomationWithShaftEngine/target/test-classes
[INFO------------------------------------------------------------------------
[INFOBUILD FAILURE
[INFO------------------------------------------------------------------------
[NFOTotal time:  1.001 s
[NFO Finished at: 2022-12-05T17:45:49+05:30
[INFO------------------------------------------------------------------------
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile[m [1m(default-testCompile)[m on project [36mwebAutomationWithShaftEngine*: [1;31mFatal error compiling: invalid target release: 17 -> [1m[Help 1]**
[ERROR 
[ ERROR To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR Re-run Maven using the -X switch to enable full debug logging.
[ERRORFor more information about the errors and possible solutions, please read the following articles:
[ERROR[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by MohabMohie** [comment]
Hi,
This means that you don't have JDK 17 installed on your machine. You need to either install it, or have a portable archive and point your IDE to its location.

This is not a bug.
