### ISSUE TITLE
Receiving get methods undefined error on maven import

### ISSUE THREAD

**Issue by netmatez** [ShaftHQ/SHAFT_ENGINE#824]
**Describe the bug**
Receiving error messages for few get methods(getDriver, getTargetBrowserName) undefined in DriverFactory helper class in with the latest master branch & latest tagged branch cloned on Jan 08, 2023.  I also do not see these methods present in the code.

**To Reproduce**
1. Download the code
2. Import as maven project in Eclipse 2020-06
3. Env: OpenJDK 14, maven 3.6.3

**Expected behavior**
Error should not be there if working code

**Screenshots**
See the pictures. 

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Just importing as maven project is showing this er
![Error](https://user-images.githubusercontent.com/77941290/211217274-307cbd2c-23e3-406b-a6d3-4e2c8ff94ac4.png)
![Error-2](https://user-images.githubusercontent.com/77941290/211217284-01af34cc-ea6d-4513-9756-ccafe88e0c15.png)
![Error-3](https://user-images.githubusercontent.com/77941290/211217288-04707e34-c06f-481a-8b6c-d14d51219375.png)
![Error-4](https://user-images.githubusercontent.com/77941290/211217290-b8459094-4de9-430a-bc27-e294eea443e5.png)
![picture-2](https://user-images.githubusercontent.com/77941290/211217294-296278bc-a2aa-4190-b916-8440fcf36e08.png)

**Comment by MohabMohie** [comment]
Hello @netmatez 
Please note that you're importing the core Engine project. You should only do this if you're objective is to contribute to SHAFT itself.
If you're trying to use the engine then we highly recommend following the steps in our readme.md

Regarding these errors, these are expected to happen on the dev branches for the coming month while we implement a certain major change, and we're handling these issues and still managing to execute all of our tests successfully from Github actions to test against all three major OSs and browser engines.
