### ISSUE TITLE
Exception in thread "main" org.testng.TestNGException:

### ISSUE THREAD

**Issue by amlosman** [ShaftHQ/SHAFT_ENGINE#825]
**Exception in thread "main" org.testng.TestNGException: **
Cannot load class from file: com.shaft.tools.listeners.AlterSuiteListener

<img width="574" alt="com shaft tools listeners AlterSuiteListener Not found" src="https://user-images.githubusercontent.com/30425773/211363333-f25e3c8e-7b56-4d8f-bc75-caeb30f734c2.PNG">
<img width="688" alt="listenersExected" src="https://user-images.githubusercontent.com/30425773/211363340-9c0cf254-741e-4db7-8f2e-c5a04cd6c0b0.PNG">
<img width="901" alt="Exception" src="https://user-images.githubusercontent.com/30425773/211363363-9690d6c1-ba86-4d14-abf8-076e07b0038d.PNG">

**Comment by MohabMohie** [comment]
Hello @amlosman ,
Please refer to these release notes 4 days ago
https://github.com/ShaftHQ/SHAFT_ENGINE/releases/tag/7.1.20230104

As of this version you should use the unified listener and update your pom.xml and test run configuration accordingly. 🙏
