### ISSUE TITLE
[Feature] checkpoints count and status attachment

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#85]
**Is your feature request related to a problem? Please describe.**
There should be specific metrics regarding the exact number of checkpoints (assertions and validations) and how many of those have passed or failed, in addition to the standard metrics for the test cases.

**Describe the solution you'd like**
Having an attachment which details this information would be beneficial.

**Comment by hernandezmshawntae** [comment]
Please and Thank You.

**Comment by MohabMohie** [comment]
Won't do.

**Comment by MohabMohie** [comment]
![Uploading CheckPoints_Report_-_Made_with_Clipchamp_AdobeExpress.gif…]()
