### ISSUE TITLE
Allure Report is Empty on MacOS

### ISSUE THREAD

**Issue by magdyheiba** [ShaftHQ/SHAFT_ENGINE#858]
**Describe the bug**
Allure Report is Empty on MacOS

**To Reproduce**
1. run any web GUI Test on MAC 
2. wait for the test to finish and the result will be opened 

**Expected behavior**
Allure report should be opened Normally 

**Screenshots**
<img width="1510" alt="Screenshot 2023-02-13 at 7 21 21 PM" src="https://user-images.githubusercontent.com/38945724/218527607-9ca09ac0-ca43-47fa-a070-c8cc58186864.png">

**Desktop (please complete the following information):**
 - OS: MAC OS : Apple M1 Pro
 - Browser [chrome]

**Additional context**
Allure-report folder 
<img width="1512" alt="Screenshot 2023-02-13 at 6 56 35 PM" src="https://user-images.githubusercontent.com/38945724/218527840-7fce08e8-2839-4aa4-a694-e9c3f0d73699.png">

**Comment by MohabMohie** [comment]
Thanks for fixing it!
