### ISSUE TITLE
[Bug]: ShaftEngine _ Teardown activities _ final page snapshot not capturing textbox inputs after test had passed

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#887]
**Describe the bug**

after test had passed ,the final snapshot in Teardown activities capturing textboxes without data. 

**Link to SHAFT_Engine Console logs**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ console logs, and link it here.
Do _NOT_ paste your full console logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include console logs!

**Link to SHAFT_Engine Extent Report HTML**
[Executtion log.txt](https://github.com/ShaftHQ/SHAFT_ENGINE/files/10793190/Executtion.log.txt)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ extent report .html file, and link it here.
https://gist.github.com/zanoon2020/3473202c038b9f993c10d76dfe11dfcf

**Environment**
 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 7.1.20230220
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS] windows 10
 4. Desktop Browser (if applicable): [e.g. chrome, safari] google chrome , microsoft edge

**To Reproduce**

1. Go to 'https://the-internet.herokuapp.com/inputs'
2. type anything on element with locator 'By.xpath//input[@type='number']'
3. wait till report is opened 
4. go to Teardown Browser instance. 
5. check the final page snap 
6. See error the field in screenshot is empty

**Expected behavior**
final snapshot must include all entered data 

**Additional context**
code I used to reach the page

@Test
	public void testShaft() {
		driver.browser().navigateToURL("https://the-internet.herokuapp.com/inputs");
		driver.element().type(By.xpath("//input[@type='number']"), "test shaft");
	}

**Comment by MohabMohie** [comment]
![image](https://user-images.githubusercontent.com/19201898/220649860-bc524247-b4ce-428d-abd7-b3cc5581d1cd.png)
issue is not visible in the attached gist / extent report. the page snapshot is only attached to the main allure report to avoid duplication.

will use the provided code to try to reproduce the issue locally.

**Comment by MohabMohie** [comment]
Further investigation shows that the element (type number) resets its value after selenium attempts to type in it. Manual validation confirms that this element should only accept number values.
https://user-images.githubusercontent.com/19201898/220653031-d982d676-e860-4bd2-9ca7-11e3ba0da441.mp4

I tested it with a number value and it gave the same result that you reported. Seems that this is the default behavior for this new W3C action. Maybe we should also add an image screenshot?

For now I will close this issue as it's behaving as expected by the manufacturers.

**Comment by zanoon2020** [comment]
> Further investigation shows that the element (type number) resets its value after selenium attempts to type in it. Manual validation confirms that this element should only accept number values. https://user-images.githubusercontent.com/19201898/220653031-d982d676-e860-4bd2-9ca7-11e3ba0da441.mp4
> 
> I tested it with a number value and it gave the same result that you reported. Seems that this is the default behavior for this new W3C action. Maybe we should also add an image screenshot?
> 
> For now I will close this issue as it's behaving as expected by the manufacturer

If it would help 
I faced same behavior with fields that accept text on another project . Thanks for investigation and support
