### ISSUE TITLE
[Bug]: Appium is giving ERROR "Remote server was still not ready after 10 minutes."

### ISSUE THREAD

**Issue by Salma2018170** [ShaftHQ/SHAFT_ENGINE#898]
**Describe the bug**
Appium is giving ERROR "Remote server was still not ready after 10 minutes."
when run Appium2 on real device 

**Link to SHAFT_Engine Console logs**

[SHAFT_Log1.txt](https://github.com/ShaftHQ/SHAFT_ENGINE/files/10819147/SHAFT_Log1.txt)
SHAFT :v7.1.20230220
Appium2
Mobile Device OS: Android
Desktop OS: win10
///////////////////////////////
*Screenshot*
![bug1](https://user-images.githubusercontent.com/76792591/221038643-22481740-03e3-478f-9ae7-abf4b81e3654.png)
![image](https://user-images.githubusercontent.com/76792591/221038685-0c1ab34e-f6f0-4054-8c05-73330e20276a.png)
![image](https://user-images.githubusercontent.com/76792591/221038720-59b41fd9-eeb6-4268-b9f6-730a6abdcf77.png)
![image](https://user-images.githubusercontent.com/76792591/221038763-6cadeecd-0bb7-4801-9e43-07adbc05a006.png)

**Comment by MohabMohie** [comment]
Hello @Salma2018170,
This is a known issue and was fixed in the latest release as per the release notes
https://github.com/ShaftHQ/SHAFT_ENGINE/releases/tag/7.1.20230222

Kindly upgrade and try again. Feel free to reopen this issue if needed.
