### ISSUE TITLE
[Feature Request]: Need to be able to take and attach a screenshot / page snapshot on demand as a browser action

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#899]
Expected output is to be able to perform the following actions

```java
driver.get().browser().captureScreenshot();
driver.get().browser().captureScreenshot(ScreenshotType.Viewport);
driver.get().browser().captureScreenshot(ScreenshotType.FullPage);
driver.get().browser().captureSnapshot();
driver.get().element().captureScreenshot(By.tagName("button"));
```

**Comment by zanoon2020** [comment]
Dear Eng @MohabMohie , 
of course "The eye does not get over the eye brow" 
I once needed the mentioned feature and developed the below code , **if it can help and save your valuable time.**



	public class CaptureScreenShot{
	  private WebDriver driver;
	  
	  
	  public CaptureScreenShot ( WebDriver driver) { 
		  
		  this.driver = driver; 
		  
	  }
	 
	Date date = new Date() ;
	SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");


	public void captureFullPageScreenshot(WebDriver driver){

		File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		
		try {
			// to create folder with date as name 
			//FileUtils.copyFile(scrFile, new File(dateFormat.format(date) + "./image.png"));
			// to create file with date as name 
			FileUtils.copyFile(scrFile, new File("./"+dateFormat.format(date) + "_fullPage.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}


	}

	public void captureElementScreenshoot( WebDriver driver , By elementLocator) {
		File scrFile =  (driver.findElement(elementLocator)).getScreenshotAs(OutputType.FILE);
		// to create file with date as name 
		try {
			FileUtils.copyFile(scrFile, new File("./"+dateFormat.format(date) + ".png"));
		} catch (IOException e) {
			e.printStackTrace();
		}
	}


my reference was : https://www.selenium.dev/documentation/webdriver/interactions/windows/#takescreenshot

Best Regards

**Comment by MohabMohie** [comment]
@zanoon2020 I'll handle this one, and you can handle the javascript click one as your first issue please. I don't want to overload your first contribution and this one is harder than I had initially sized it based on our discussion yesterday
