### ISSUE TITLE
Allure report return with NaN after deploy 7.1.20230222

### ISSUE THREAD

**Issue by sultanpaymob** [ShaftHQ/SHAFT_ENGINE#917]
7.1.20230222

<img width="1300" alt="Screenshot 2023-02-26 at 8 57 54 PM" src="https://user-images.githubusercontent.com/109296848/221430999-2a123bd2-b476-418a-981d-03fe94619670.png">

<img width="1800" alt="Screenshot 2023-02-26 at 8 53 42 PM" src="https://user-images.githubusercontent.com/109296848/221430839-fbab4e76-15e2-43e5-b042-894cd184bbea.png">

**Comment by MohabMohie** [comment]
can you please provide the requested gist, and information about your OS?
we will also need a screenshot from the generate_allure_report.bat/sh file

**Comment by MohabMohie** [comment]
@magdyheiba can you support with this? If I remember correctly you had a similar issue and was able to fix it.

**Comment by magdyheiba** [comment]
@sultanpaymob  Can you please provide me the needed info that Mohab mentioned ? 
I was unable to reproduce the issue on my local machine 
<img width="1509" alt="Screenshot 2023-03-07 at 11 04 34 PM" src="https://user-images.githubusercontent.com/38945724/223552332-2b4e121b-a86a-4ca3-95e3-e8d7c29b6ef5.png">

**Comment by MohabMohie** [comment]
@sultanpaymob I'll close for now due to lack of activity, but please feel free to reopen with the required information.
