### ISSUE TITLE
[Feature Request]: Technical debt -  apply some linting to reduce code complexity

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#921]

**Comment by blacelle** [comment]
Hi @MohabMohie .
I'm working on a maven plugin, to apply linting rules based on `.cleanthat/cleanthat.yaml` over the whole repository (while the Guithub App process only the files modified in each PullRequest).

From the root of your repository, you may go with:

> mvn io.github.solven-eu.cleanthat:cleanthat-maven-plugin:cleanthat

or 

> mvn io.github.solven-eu.cleanthat:cleanthat-maven-plugin:2.6:cleanthat

Some very limited documentation is available at https://github.com/solven-eu/cleanthat/tree/master/maven.
List of available linters is available at https://github.com/solven-eu/cleanthat/tree/master/maven
