### ISSUE TITLE
[Bug]: SHAFT_Reporting _ Generated allure report Archive doesn't contain allure results folder 

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#951]
**Describe the bug**

generated allure archive doesn't contain allure results folder 

**Link to SHAFT_Engine Console logs**
https://gist.github.com/zanoon2020/d28568664124024d127da82fc50b0540

time stamps for the issue :
you can start investigation from line 126 in attached shaft console logs

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):7.1.20230309  
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS]10
 4. Desktop Browser (if applicable): [e.g. chrome, safari]not related to borowser

**To Reproduce**

1. in reporting.properties set 

generateAllureReportArchive=true
openAllureReportAfterExecution=true
generateExtentReports=true
cleanExtentReportsDirectoryBeforeExecution=true

2. run any test 
3. go to project path
4. open the generated archive 
5. observe no report opened 

**Expected behavior**

generated archive must contain allure results inside it 

**Screenshots**

![image](https://user-images.githubusercontent.com/65794900/224746648-fb9dda39-f85a-48a9-8db5-3e9099addda6.png)

**Comment by MohabMohie** [comment]
something is wrong with the command...
`[90m04:56:24 PM[m  [90m@main              [m | [38;2;0;96;168mcom.shaft.tools.io.ReportManager          [m | [38;2;67;176;42;1mINFO [m | Executing: ".\C:\Users\Zanoon\.m2\repository\allure\allure-2.21.0/bin/allure.bat generate 'allure-results' -o 'generatedReport/allure-report'" locally.
`

I'm afraid to ask you to update your windows... but I think you need to... or at least update your powershell installation.

This looks like a CLI module compatibility issue with windows 10 :D
