### ISSUE TITLE
[Bug]: SHAFT_Reporting_execution log attached in allure report not capturing all suiteTeardown steps

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#954]
**Describe the bug**

the SHAFT Engine Logs - Execution log file not capturing all the steps of suiteTeardown

**Link to SHAFT_Engine Console logs**
logs attached in allure report 
https://gist.github.com/zanoon2020/94c1ca952b18a6460c239c3008120170

logs from eclipse console 
https://gist.github.com/zanoon2020/92974df538754f83229211763ec83e68

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 0309

 3. Desktop OS: [e.g. iOS] win 10 
 4. Desktop Browser (if applicable): [e.g. chrome, safari] not related to browser 
 

**To Reproduce**

run any test 
compare the logs in ide console and log attached in allure report 

**Expected behavior**
both reports must be the same

**Screenshots**

![image](https://user-images.githubusercontent.com/65794900/225010278-16042b48-ad6a-45bf-a31d-88106e2253ae.png)

![image](https://user-images.githubusercontent.com/65794900/225010394-777193a8-35b0-4133-84c5-af178fb6df65.png)

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy 
Need your help to triage and understand the problem better.

**Comment by MahmoudElSharkawy** [comment]
@MohabMohie 
After investigating, this is happening due to that the **@AfterSuite** in **ConfigurationHelper** class, **suiteTeardown()** method is **executing before** the **TestNGListener**, **onExecutionFinish()** method. 
Tried various approaches to go around this, but nothing worked so far. Any idea how to approach this?

**Comment by MahmoudElSharkawy** [comment]
@zanoon2020 After comparing the 2 logs, I found that the difference is only in some ending logs regarding attaching the generating different report + the engine closure logs (screenshot attached)..
Please tell us more as why you really need this info to be included in the logs attachment; Is this info really needed for you?

![image](https://user-images.githubusercontent.com/46620378/227512532-70e39b18-ee5c-41db-88d2-fddea41f05b8.png)

**Comment by zanoon2020** [comment]
Dear @MahmoudElSharkawy no it's not really needed for me , it was first discovered when i was investigating creating allure archive after execution , and i didn't find the logs in tear down logs . I raised this bug just for consistency between console log and SHAFT  generated log .

**Comment by MahmoudElSharkawy** [comment]
> Dear @MahmoudElSharkawy no it's not really needed for me , it was first discovered when i was investigating creating allure archive after execution , and i didn't find the logs in tear down logs . I raised this bug just for consistency between console log and SHAFT generated log .

@zanoon2020 Ofcourse, thank you for your continuous contribution and dedication to open bugs and to enhance the engine.

@MohabMohie What do you think; Should we close this one?

**Comment by MahmoudElSharkawy** [comment]
Will close this for now. Please feel free to reopen if needed.
