### ISSUE TITLE
[Bug]: User can't override appium capabilities 

### ISSUE THREAD

**Issue by hossameldinmohamed** [ShaftHQ/SHAFT_ENGINE#962]
**Describe the bug**

"**Multiple entries with same key: appium:fullReset=false and appium:fullReset=true** " exception thrown when user has the mobile application already installed on the device and wanted to set mobile_fullReset=false

**Environment**

 1. SHAFT_Engine version :  7.1.20230315

1. Go to 'MobileCapabiliies.properties'
2. add 'mobile_fullReset=false' 
3. run your tests '....'

**Expected behavior**

When user has the mobile application already installed on the device and doesn't want to remove the app every time the tests executed he should be able to use mobile_fullReset=false  with no issue
 

**Screenshots**

<img width="1359" alt="Screenshot 2023-03-16 at 8 43 52 AM" src="https://user-images.githubusercontent.com/11408969/225563953-48c7103b-563e-410b-8489-f4ee2f06495f.png">

**Comment by MohabMohie** [comment]
@Mohab-Osama closed this issue and a new release has been pushed with the fix.

@hossameldinmohamed kindly upgrade and try now. Feel free to reopen the ticket if the issue can be reproduced.
