### ISSUE TITLE
[Bug]: Adjust "attemptRemoteServerPing" to check status without "/" or adding flag to disable this check

### ISSUE THREAD

**Issue by roaamagdy** [ShaftHQ/SHAFT_ENGINE#963]
**Problem:**

To run against remote execution, SHAFT first make ping request to the server to check its status using `status/` or `wd/hub/status/`,
some servers response with `404` although it is up and running that's happen as the status call ends with `/` and some servers doesn't support it. They support status call without `/` at the end.

Reference code is [here](https://github.com/ShaftHQ/SHAFT_ENGINE/blob/main/src/main/java/io/github/shafthq/shaft/driver/DriverFactoryHelper.java?fbclid=IwAR2UO6MPX59gnY7cOJe_ArtjB3ma4ELs4Z29rtS3iHpTcd9gQy_HCm-rbcM#L599)

**Suggestions:**

- Add another call to `status` without `/` in case 404 returned from first request
- Add flag to disable this check if needed

**Note**: This issue blocks the tests execution on some servers

**Comment by roaamagdy** [comment]
@MohabMohie Do you have timeline when this issue can be fixed?

**Comment by MohabMohie** [comment]
@magdyheiba in this issue we need to implement a feature flag to disable the remote server connection checks. Which is essentially a new property on the flags file, and if it's enabled we skip this check and go directly to try connecting to the remote server.

**Comment by roaamagdy** [comment]
@MohabMohie is it possible to add the `status` method in the property files as well? you can set default to `status/ ` and user will have the option to change it if needed?

**Comment by MohabMohie** [comment]
@roaamagdy actually this connection check is not needed in most cases, it's only needed in case of SHAFT initiating its own Grid or Appium Server.

**Comment by roaamagdy** [comment]
@MohabMohie when you will release this fix?

**Comment by roaamagdy** [comment]
@MohabMohie @magdyheiba When I updated to the new release and set the executionAddress to our server I got this issue: 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/39972999/229384841-669c02b9-6487-4b85-b370-29053f01de50.png">

**Comment by MohabMohie** [comment]
@roaamagdy 
Would you kindly share the full stacktrace and the properties you're using please?

**Comment by roaamagdy** [comment]
@MohabMohie I am using the default properties , nothing changed except the "`executionAddress`" 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/39972999/229385225-c8d5b0fc-6805-4e0f-a1b3-657fc1e134b6.png">

**Comment by MohabMohie** [comment]
We need the full stacktrace please.

**Comment by roaamagdy** [comment]
This is what is before the exception (the capabilities) 

<img width="847" alt="image" src="https://user-images.githubusercontent.com/39972999/229386081-6eaa6a1b-44c3-43db-9867-29de25221b6d.png">

**Comment by MohabMohie** [comment]
Is there something that prevents you from sharing the full exception stacktrace?

**Comment by roaamagdy** [comment]
@MohabMohie there is nothing more to be shared. The first lines in the log just some logs then the log print the capabilities then the exception I shared.

**Comment by MohabMohie** [comment]
The second screenshot wasn't loaded.
Regarding launching the driver I recommend using the configuration manager to generate the correct platform and mobile properties then launching the driver using
driver = SHAFT.GUI.WebDriver.getInstance();

Meanwhile I'll try to reproduce this issue as it's not reproducible via github actions or locally.

**Comment by roaamagdy** [comment]
@MohabMohie I have to set some capabilities and you advised before to use this way in initializing the driver
`new SHAFT.GUI.WebDriver(CHROME,capabilities)`

Regarding the properties file, I deleted the old ones and I let shaft generated and it works locally but when I changed the `executionAddress` to remote server, I got this exception

**Comment by roaamagdy** [comment]
Issue is fixed, there was conflict in the dependencies
