### ISSUE TITLE
[Bug]:  "setRemoteDriverInstance" failed. "Failed to connect to remote server.". - Issue still exists

### ISSUE THREAD

**Issue by sultanpaymob** [ShaftHQ/SHAFT_ENGINE#996]
@MohabMohie 

              Issue still exists

![Screenshot 2023-03-28 at 9 56 20 PM](https://user-images.githubusercontent.com/109296848/228353665-7639199f-fa7f-4050-8f6b-d05bfb5c4d65.png)
![Screenshot 2023-03-28 at 9 56 50 PM](https://user-images.githubusercontent.com/109296848/228353777-6be6c08a-9afa-4e55-8e3b-54bc321484a7.png)
![Screenshot 2023-03-28 at 10 06 10 PM](https://user-images.githubusercontent.com/109296848/228354560-ba8804e0-8669-4360-9fba-fe3236cfeb36.png)

Log.txt
[Log.txt](https://github.com/ShaftHQ/SHAFT_ENGINE/files/11093774/Log.txt)

_Originally posted by @sultanpaymob in https://github.com/ShaftHQ/SHAFT_ENGINE/issues/947#issuecomment-1487521868_

**Comment by magdyheiba** [comment]
@sultanpaymob  Can you please set the platformVersion to be "13.0" ? it should work

**Comment by sultanpaymob** [comment]
@magdyheiba the same like behavior

**Comment by MohabMohie** [comment]
@sultanpaymob 
Kindly upgrade to the latest 28/3 release, reset your properties files to the default, reconfigure and try again.

We disabled this check by default now so your code shouldn't even go in that flow.
